### ISSUE TITLE
Minor: NSNumber when NSString expected

### ISSUE THREAD

**Issue by pronebird** [magicalpanda/MagicalRecord#1001]
For the sake of consistency:

https://github.com/magicalpanda/MagicalRecord/blob/d18e74fe435359238b9593c03e41c1ee0baa0b78/MagicalRecord/Categories/NSManagedObject/NSManagedObject%2BMagicalRequests.m#L145

this should be `NSString` not `NSNumber`. `NSString` supports `boolValue` too.

**Comment by tonyarnold** [comment]
Fixed by ece79cc744effefd20d09e96ef2a5836d9956739.
