### ISSUE TITLE
saveWithBlock simple dont work?

### ISSUE THREAD

**Issue by DigitalForms** [magicalpanda/MagicalRecord#1002]
Entity *new = [Entity MR_createEntity];
    new.test = @"abc";
    [MagicalRecord saveWithBlock:^(NSManagedObjectContext *localContext) {
        Entity *newlocal = [new MR_inContext:localContext];
        newlocal.test = @"test";
        for (Entity *entity in [Entity MR_findAll])
        {
            NSLog(@"Block: %@", entity);
        }
    } completion:^(BOOL success, NSError *error) {
        for (Entity *entity in [Entity MR_findAll])
        {
            NSLog(@"Complete: %@", entity);
        }
    }];

Am i doing something wrong? In complete all should be writen to store, and shoud show value @"test" in attribute test right? It just dont.

**Comment by Alydyn** [comment]
You need to save `new` prior to trying to access it in the `saveWithBlock:`
This line:
`Entity *newlocal = [new MR_inContext:localContext];` requires that `new` has been saved to the persistent store first.

```objC
Entity *new = [Entity MR_createEntity];
new.test = @"abc";

[new MR_saveToPersistentStoreAndWait]; //add this, or some other save method

[MagicalRecord saveWithBlock:^(NSManagedObjectContext *localContext) {
    Entity *newlocal = [new MR_inContext:localContext];
    // etc...
```

This is a fundamental aspect of Core Data and has nothing to do with MagicalRecord.

**Comment by DigitalForms** [comment]
Thank you sir, topic is closed.
