### ISSUE TITLE
NSFetchedResultsController initWithFetchRequest not working

### ISSUE THREAD

**Issue by MichealB1969** [magicalpanda/MagicalRecord#1004]
Using version 2.3 NSFetchedResultsController initWithFetchRequest does not return any objects, despite knowing there are objects available.

```objective-c
NSFetchRequest * fetchRequest = [SomeObject MR_requestAllSortedBy:@"created" ascending:NO];
//[request setFetchLimit:100];  
[request setFetchBatchSize:20];  

NSManagedObjectContext* managedObjectContext = [NSManagedObjectContext MR_defaultContext];
NSFetchedResultsController* fetchedResultsController = [[NSFetchedResultsController alloc] initWithFetchRequest: fetchRequest managedObjectContext: managedObjectContext sectionNameKeyPath:nil cacheName:nil];
```

What am i missing?

Thanks,
Mike

**Comment by tonyarnold** [comment]
Hi Mike, the code you've posted should work OK. Can you check the managed object context and fetch request are not nil?

**Comment by MichealB1969** [comment]
Thanks, my mistake fixed.

On Sunday, May 10, 2015, Tony Arnold <notifications@github.com> wrote:

> Hi Mike, the code you've posted should work OK. Can you check the managed
> object context and fetch request are not nil?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/magicalpanda/MagicalRecord/issues/1004#issuecomment-100712865>
> .
>


-- 
Mike

Mike Barlow
Founder & CEO
myHealthPal Group

UK M: +44 7557 247 247
US L:  +1 (646) 808 0765

<http://myhealthpal.com>  <http://fb.com/MyHealthPal>
<http://uk.linkedin.com/in/michealbarlow>
<http://about.me/michealbarlow.com>  <http://twitter.com/michealb1969>
<http://michealbarlow.com>

**Comment by tonyarnold** [comment]
Good to hear — feel free to share what was going wrong so that others can refer to this issue in future if you want to.

**Comment by MichealB1969** [comment]
Will do, I didn't call perform fetch afterwards in the right place.

On Sunday, May 10, 2015, Tony Arnold <notifications@github.com> wrote:

> Good to hear — feel free to share what was going wrong so that others can
> refer to this issue in future if you want to.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/magicalpanda/MagicalRecord/issues/1004#issuecomment-100713090>
> .
>


-- 
Mike

Mike Barlow
Founder & CEO
myHealthPal Group

UK M: +44 7557 247 247
US L:  +1 (646) 808 0765

<http://myhealthpal.com>  <http://fb.com/MyHealthPal>
<http://uk.linkedin.com/in/michealbarlow>
<http://about.me/michealbarlow.com>  <http://twitter.com/michealb1969>
<http://michealbarlow.com>
