### ISSUE TITLE
v2.3 has been in beta 5 for over 6 months

### ISSUE THREAD

**Issue by joejcon1** [magicalpanda/MagicalRecord#1005]
I feel as though this should either be tagged a full release or the documentation should list any known issues/reasons why this is not a full release. The repository currently insinuates that there is no stable production version of MagicalRecord.

**Comment by darecki** [comment]
Good point.

**Comment by tonyarnold** [comment]
Hi guys, it's just been a matter of time — I have a new baby in the house, and haven't made time for MagicalRecord. There was a small list of pretty annoying bugs in 2.3-beta.5 — I believe they're all resolved, and I'm finalising the `module-support` branch, which includes some support for working with Swift. 

If either of you want to document that list of issues/reasons, this is an open source project — contributions from people using the library in their products are always welcome.

**Comment by tonyarnold** [comment]
Version 2.3.0 is out now.
