### ISSUE TITLE
overriding CocoaLumberjack LOG_LEVEL_DEF

### ISSUE THREAD

**Issue by FloresRobles** [magicalpanda/MagicalRecord#1010]
the line:

```objective-c
#define LOG_LEVEL_DEF (DDLogLevel)[MagicalRecord loggingLevel]
```

in MagicalRecordLogging.h 

currently overrides the configuration for cocoalumberjack

**Comment by tonyarnold** [comment]
Does removing the define still allow CocoaLumberjack to do what it needs to? I don't use it, so I haven't tested any of that code.

**Comment by tonyarnold** [comment]
Fixed by c7a378d04cbc2efbc3a67113005cbbeeb60f90dd.

**Comment by FloresRobles** [comment]
removing it throws the error: **Use of undeclared identifier 'ddLogLevel'**
that's because MRLogError uses LOG_MAYBE which uses LOG_LEVEL_DEF which cocoalumberjack defines as ddLogLevel which is set in a per file basis

**Comment by FloresRobles** [comment]
I propose #1013

**Comment by tonyarnold** [comment]
Works for me! Merged, thanks!
