### ISSUE TITLE
Which version of MagicalRecord to choose.

### ISSUE THREAD

**Issue by czaku** [magicalpanda/MagicalRecord#1017]
Hi guys,

I am working on some project and the current CoreData setup is very messy and wrong. I am trying to port it to MagicalRecord, but am a bit confused which version of MagicalRecord to choose for a product that is life and needs to work well and stable. 
It is an iOS >7.0 app that is for now iPhone only, the database structure is not very complex or big. 
Any suggestions and help appreciated. I have started with version 2.2 through CocoaPods but am wondering if this is the right choice.

Thanks

**Comment by Alydyn** [comment]
I recommend [version 2.3.0beta6](https://github.com/magicalpanda/MagicalRecord/releases/tag/v2.3.0-beta.6),

**Comment by vitalys** [comment]
+1

**Comment by tonyarnold** [comment]
Yeah, go with 2.3.0-beta.6 at the moment. It's what I'm actively working on. Once 2.3 is out, I'll switch tack back to 3.0 again, but that could be a little while yet.
