### ISSUE TITLE
Manual installation doesn't work with umbrella header anymore

### ISSUE THREAD

**Issue by cbscd** [magicalpanda/MagicalRecord#1019]
I manually import the source files in my project following the instructions, but when I add the #import "MagicalRecord.h" Xcode complains about the imported files in it.

For example:
.../MagicalRecord/MagicalRecord.h:17:9: 'MagicalRecord/Core/MagicalRecordInternal.h' file not found.

**Comment by bwearley** [comment]
I'm having this issue as well in both the dev branch and the 2.3.0 beta 6 release. Not sure if I'm just a noob or missing something or what, but the #import statements in the MR files seem to be completely out of sync with the actual file/folder structure of MR.

**Comment by tonyarnold** [comment]
No, you're not a noob — I changed things in 2.3b6, and it looks like maybe I broke manually importing sources. The focus was on dynamic frameworks, so I didn't test the other options as much (or at all, in this case).

**Comment by Mozilla9** [comment]
I have a same issue. Manual importing is broken.

For visibility of framework headers in your project need just add the next string to .xcconfig file (or via BuildSettings->SearchPaths->UserHeadersSearchPaths)

Example for the AFNetworking:
USER_HEADER_SEARCH_PATHS = $(inherited) "${SRCROOT}/<PATH-TO-FRAMEWORK>/AFNetworking.framework/Headers"

This lets use a manual importing and standalone framework.

**Comment by tonyarnold** [comment]
This should be fixed by #1018.

**Comment by cbscd** [comment]
Thanks @tonyarnold
