### ISSUE TITLE
Light Weight Migration

### ISSUE THREAD

**Issue by m177312** [magicalpanda/MagicalRecord#1020]
Version 1 of the app is deployed in the app store and [MagicalRecord setupAutoMigratingCoreDataStack]; was used. Version 1 contains data which is locally stored on devices. Version 2 needs to fetch this data. However, I am unable to retrieve this. I have tried the other solutions posted, but none of them have worked so far.

**Comment by Alydyn** [comment]
Need a lot more info than that.  What version of MR?  Did you create a new model version in the Model Editor in Xcode?  Did you re-generate your subclasses?  What failure(s) are you seeing?
