### ISSUE TITLE
The 2.2 Release is GONE

### ISSUE THREAD

**Issue by samkrishna** [magicalpanda/MagicalRecord#1023]
So, I guess this is directed to @tonyarnold:

Exactly why is the 2.2 release tag GONE when all the pre-2.2 release tags still seem to be intact?

This tag deletion broke the build for a company project where we were explicitly using the 2.2 tag since all 2.3 betas seemed too unstable at the time (back in early 2014) to use.

Now I'm going to have to go and figure out which hash value to use in my Podfile because of this move. Awesome.

**Comment by tonyarnold** [comment]
The 2.2 release tag is still there: 77ea00a600209c452ab9c374e69492676c1280ab and https://github.com/magicalpanda/MagicalRecord/releases/tag/2.2

Awesome indeed.

**Comment by samkrishna** [comment]
Actually, I can see I wasn't clear in my initial write-up. So here's attempt #2:

This issue may be sourced back to CocoaPods, but I can't actually use CocoaPods anymore to reach the 2.2 release explicitly. CocoaPods seems to pull against **head** since it doesn't find the 2.2 tag.

I've been able to reproduce this issue on a fresh install of Yosemite (10.10.3) as well as on my Developer machine, which has been incrementally upgraded over the years.

This is using the latest CocoaPods, v. 0.37.2.

**Comment by tonyarnold** [comment]
How are you locking the version in your Podfile? All of the newer releases are of the format `v2.3.0`, whereas the 2.2 tag is just `2.2`.

**Comment by samkrishna** [comment]
I'm using "2.2"

**Comment by iv-mexx** [comment]
Installing MagicalRecord 2.2 with Cocoapods 0.37.2 works for me, no problem. 
The line in the Podfile: `pod 'MagicalRecord', '2.2'`
