### ISSUE TITLE
CoreData notification not getting called

### ISSUE THREAD

**Issue by KieranMcGrady** [magicalpanda/MagicalRecord#1027]
I previously commented about this on issue #196 but as that is quite an old issue and there have been lots of revisions to MR since I thought it might be best to open a new issue.

When I use the ```saveWithBlock``` method the CoreData saved/changed notifications are not getting called. I am 100% sure the data is getting saved and merged to the main thread (if I update my UI manually the new data shows) but the notifications are not called.

Here is a code sample. I am doing the same within a completion block of an NSOperation.

```objective-c
        [op start:^(NSError *error, NSArray *array) {
            if (!error) {
                if (array) {
                    [MagicalRecord saveWithBlock:^(NSManagedObjectContext *localContext) {
                        for (MyObject *m in array) {
                            NSArray *t = [MyObject MR_findAllWithPredicate:[NSPredicate predicateWithFormat:@"uid = %@", m.uid] inContext:localContext];
                            
                            if (t.count > 0) {
                                MyObject *myObject = [t firstObject];
                                if (conditionMet) {
                                    [myObject setNumber:[NSNumber numberWithUnsignedInt:m.numberValue]];
                                }
                            }
                        }
                    } completion:^(BOOL contextDidSave, NSError *error) {
                        
                    }];
                }
            }
        }];
```

I'd really appreciate some help with this. I'm currently using ```MR_saveToPersistentStoreWithCompletion``` throughout my app but the performance of ```saveWithBlock``` is fantastic for my UI. If I can get the notifications working I would have the perfect solution.

NB: I am using the latest version of MR available on Cocoapods.

**Comment by Alydyn** [comment]
When you say notifications are not getting called, what `NSManagedObjectContext` are you expecting to hear notifications from?

**Comment by KieranMcGrady** [comment]
I would expect that one the changes are merged to the main context I'd get a notification for MR_defaultContext.

**Comment by Alydyn** [comment]
You should expect notifications for `MR_rootSavingContext` and the `localContext` as those are actually getting saved.  The only thing Magical Record does to the `MR_defaultContext` is tell it to call `-mergeChangesFromContextDidSaveNotification`.  It doesn't call `-save:` on the `MR_defaultContext`.  If you are looking for save notifications in your example you should register to receive them from the `MR_rootSavingContext`.

**Comment by KieranMcGrady** [comment]
Thanks. So I tried listening to ```MR_rootSavingContext``` instead but my UI just locks and the save completion block is never called.

**Comment by Alydyn** [comment]
You probably need to handle the notification on the main queue, but it's getting sent on a background queue.  I always wrap my `NSNotification` handlers like so:
```objC
- (void)handleSomeNotification:(NSNotification *)note
{
    [NSOperationQueue mainQueue] addOperationWithBlock:^ {
       //do something, probably UI related, that should be on main queue
    }]; 
)
```

**Comment by KieranMcGrady** [comment]
Perfect! It's working now that I wrapped the notification handler as you suggested. Thanks for your help on this!

**Comment by Alydyn** [comment]
Good to hear!
