### ISSUE TITLE
MR_createEntityInContext

### ISSUE THREAD

**Issue by ghe0106** [magicalpanda/MagicalRecord#1030]
have replaced all calls in code for MR_createInContext with MR_createEntityInContext - but now getting 
message that MR_createEntityInContext is deprecated and to replace it with MR_createEntityInContext ?? is this and xcode issue ?

**Comment by tonyarnold** [comment]
As far as I can remember (and see in the header) `MR_createEntityInContext` is not deprecated. Do you want to post:

- The full error
- What version of Xcode you're using

I'll see if I can help.

**Comment by ghe0106** [comment]
sample section of my code ...
  if (message.threadID.integerValue != -1) {
                 
                 // group message, just add to the thread
                 NSPredicate *predicate = [NSPredicate predicateWithFormat:@"%K == %@", @keypath(MessageThread.new, threadID), message.threadID];
                 NSArray *existingThreads = [MessageThread MR_findAllWithPredicate:predicate inContext:localContext];
                 if (existingThreads.count != 0)
                     thread = existingThreads[0];
                 else {
                     thread = [MessageThread MR_createEntityInContext:localContext];
                 }
                 
                 NSPredicate *recipientPredicate = [NSPredicate predicateWithFormat:@"%K == %@", @keypath(Recipient.new, recipientID), message.senderID];
                 NSArray *existingRecipient = [Recipient MR_findAllWithPredicate:recipientPredicate inContext:localContext];
                 Recipient *recipient = [existingRecipient lastObject];
                 if (recipient) {
                     [thread addInvolvedRecipientsObject:recipient];
                 }
             }
             else {
                 NSPredicate *threadPredicate = [NSPredicate predicateWithFormat:@"threadID == -1 AND ANY involvedRecipients IN %@",
                                                 message.recipients];
                 NSArray *existingThread = [MessageThread MR_findAllWithPredicate:threadPredicate inContext:localContext];
                 thread = [existingThread lastObject];
                 if (!thread) {
                     thread = [MessageThread MR_createEntityInContext:localContext];
                     thread.threadID = @(-1);
                     [thread addInvolvedRecipients:message.recipients];
                 }
                 
                 [thread addMessagesObject:message];
             }
I have 34 warnings - essentially everywhere In using cMR_createEntityIn Context - and xcode advises that it deprecated and will be removed in 4.0
full error:
/Users/georgeeaston/Desktop/iOS Workspace/Chameleon/Chameleon/ComposeMessagesViewController.m:318:49: 'MR_createEntityInContext:' is deprecated: This method has been deprecated and will be removed in MagicalRecord 4.0. Please use `MR_createEntityInContext:` instead.
Im currently using Xcode Version 6.3.2 (6D2105)

**Comment by tonyarnold** [comment]
There must be something wrong with the copy of MagicalRecord in your project. Looking at the source to both the released version (2.3.0) and the development release (3.0.0) neither has deprecated `+[NSManagedObject MR_createEntityInContext:]`. Can you have a look at the header for `NSManagedObject+MagicalRecord.h` and see what the `MR_createEntityInContext:` method looks like there please?

**Comment by ghe0106** [comment]
in the header file:

+ (instancetype) MR_createEntityInContext:(NSManagedObjectContext *)context;

in the code file:

+ (id) MR_createEntityInContext:(NSManagedObjectContext *)context
{
    if ([self respondsToSelector:@selector(insertInManagedObjectContext:)] && context != nil)
    {
        id entity = [self performSelector:@selector(insertInManagedObjectContext:) withObject:context];
        return entity;
    }
    else
    {
        NSEntityDescription *entity = nil;
        if (context == nil)
        {
            entity = [self MR_entityDescription];
        }
        else
        {
            entity  = [self MR_entityDescriptionInContext:context];
        }
        
        if (entity == nil)
        {
            return nil;
        }
        
        return [[self alloc] initWithEntity:entity insertIntoManagedObjectContext:context];
    }
}

**Comment by KorvinSzanto** [comment]
These look to be marked as deprecated to me: https://github.com/magicalpanda/MagicalRecord/blob/c7b14f658b4fca32f8d33f8f76160203053ce4b9/MagicalRecord/Categories/NSManagedObject/NSManagedObject%2BMagicalRecord.h#L68-L74 no?

**Comment by championofblocks** [comment]
I was seeing this issue in my local copy of 2.3.0-beta5 but updating to v2.3.2 has fixed the warning.

It was originating from `NSManagedObject+MagicalRecord.h` in the `MagicalRecordDeprecated` category where 

```objective-c
+ (instancetype) MR_createInContext:(NSManagedObjectContext *)context MR_DEPRECATED_WILL_BE_REMOVED_IN_PLEASE_USE("4.0", "MR_createEntityInContext:");
- (BOOL) MR_deleteInContext:(NSManagedObjectContext *)context MR_DEPRECATED_WILL_BE_REMOVED_IN_PLEASE_USE("4.0", "MR_deleteEntityInContext:");
```
was actually reading as

```objective-c
+ (instancetype) MR_createEntityInContext:(NSManagedObjectContext *)context MR_DEPRECATED_WILL_BE_REMOVED_IN_PLEASE_USE("4.0", "MR_createEntityInContext:");
- (BOOL) MR_deleteEntityInContext:(NSManagedObjectContext *)context MR_DEPRECATED_WILL_BE_REMOVED_IN_PLEASE_USE("4.0", "MR_deleteEntityInContext:");
```

It's clear to see where the issue lay: the methods were marked as deprecated and the suggested replacements were the deprecated methods.

No longer seeing this and I don't even see it in the remote copy here in the repo. 

I think this issue can be closed now @ghe0106 @tonyarnold

**Comment by tonyarnold** [comment]
Thanks @championofblocks!
