### ISSUE TITLE
Duplicate functionality?

### ISSUE THREAD

**Issue by pronebird** [magicalpanda/MagicalRecord#1032]
Hi,

Just stumbled upon these two methods that seem to duplicate each other's functionality:

```objc
NSFetchedResultsController *controller = [ExpenseModel MR_fetchAllSortedBy:@"placedAt" ascending:NO withPredicate:nil groupBy:@"monthYearSection" delegate:self];
```

```objc
NSFetchedResultsController *controller = [ExpenseModel MR_fetchAllGroupedBy:@"monthYearSection" withPredicate:nil sortedBy:@"placedAt" ascending:NO delegate:self];
```

Am I right and shall we refactor API in upcoming release?

**Comment by tonyarnold** [comment]
Sorting does what you'd expect — it sorts the returned entities using the key you pass. 

Grouping does something altogether different: it groups returned entities by the passed key, which essentially means that the ordering will first be based upon the group, and within each group it is then sorted by the passed key. 

A common use of grouping is for things like blog entries — you want to group by month, and then sort by day.

**Comment by pronebird** [comment]
I am not sure how it makes any difference in terms of "GROUP BY ORDER BY" query. I get absolutely the same SQL query for MR_fetchAllGroupedBy or MR_fetchAllSortedBy. The latter calls "MR_fetchAllGroupedBy" internally and then "MR_fetchAllGroupedBy" calls "MR_requestAllSortedBy". It's like a maze. I think API should refined.

**Comment by tonyarnold** [comment]
Sure, I agree — it's a bit of a minefield in there. You're welcome to submit a PR, otherwise I'll look into it when I have some time. Thanks for the heads up.
