### ISSUE TITLE
cocoapods use_frameworks! pod MagicalRecord, pod CocoaLumberJack

### ISSUE THREAD

**Issue by justdevelopers** [magicalpanda/MagicalRecord#1040]
Podfile

target 'Module2' do
	use_frameworks!
	pod 'CocoaLumberjack'
	pod 'MagicalRecord'
end

Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_DDLog", referenced from:
      objc-class-ref in MagicalRecord+ErrorHandling.o
      objc-class-ref in NSManagedObject+MagicalDataImport.o
      objc-class-ref in NSManagedObject+MagicalRecord.o
      objc-class-ref in NSManagedObjectContext+MagicalObserving.o
      objc-class-ref in NSManagedObjectContext+MagicalRecord.o
      objc-class-ref in NSManagedObjectContext+MagicalSaves.o
      objc-class-ref in NSObject+MagicalDataImport.o
      ...
In my project I have both CocoaLumberjack as MagicalRecord in my Podfile. I solved it by adding CocoaLumberjack.framework to the Link Binary With Libraries in the Pods-MagicalRecord target my Pods project has, but I am not sure that is the way to go.

**Comment by Ziewvater** [comment]
@justdevelopers I am having the exact same issue. Your solution works, but running `pod install` again will break it when the Pods project is regenerated.

**Comment by pzearfoss** [comment]
So glad I found this.  

Is this a bug with MagicalRecord or is it cocoapods problem?

**Comment by Ziewvater** [comment]
@pzearfoss this thread seems to be a copy of [this](https://github.com/magicalpanda/MagicalRecord/issues/988) issue. The other issue seems to have more of a conversation going on, and would probably be the better one to follow.

**Comment by pzearfoss** [comment]
@Ziewvater - awesome, thanks for pointing me to that.

**Comment by pavm035** [comment]
Any update on this?

**Comment by tonyarnold** [comment]
This is a duplicate of #988.
