### ISSUE TITLE
Erroneous @end's in MagicalRecordShorthandMethodAliases.h

### ISSUE THREAD

**Issue by donamiteistnt** [magicalpanda/MagicalRecord#1043]
I am using the "develop" branch and have noticed after updating that commit b50a80355ae0458ea5a01308aed8b85652ea4491 has introduced a bug: MagicalRecordShorthandMethodAliases.h has an erroneous @end on line 29 and another on line 166.

**Comment by Alydyn** [comment]
fix and submit a pull request :wink:

**Comment by donamiteistnt** [comment]
Uh, yeah (duh). :blush: You are of course correct.  I'm on it!
