### ISSUE TITLE
A thread error

### ISSUE THREAD

**Issue by seanLee** [magicalpanda/MagicalRecord#1050]
Hello,
that's my code 

````objective-c
 Product_category *p_category = [weakSelf.fetchController.fetchedObjects objectAtIndex:_carousel.currentItemIndex];
    NSDictionary *dic = @{@"category_id":p_category.id};
    NSArray *productArray = [Product MR_findByAttribute:@"category_id" withValue:p_category.id];
    //removeAll and set page 1
    [[NetAPIManager sharedManager] request_products:[NSDictionary accessTokenSortedDic:dic isAuth:YES] withBlock:^(id data, NSError *error) {
        if (error) {
            [error showErrorInfo];
            return;
        }
        if (data) {
            [weakSelf.dataItems removeAllObjects];
            [MagicalRecord saveWithBlock:^(NSManagedObjectContext *localContext) {
                for (Product *curProduct in productArray) {
                    Product *localProduct = [curProduct MR_inContext:localContext];
                    [localProduct MR_deleteEntity];
                }
            } completion:^(BOOL contextDidSave, NSError *error) {
                [data enumerateObjectsUsingBlock:^(id obj, NSUInteger idx, BOOL *stop) {
                    [weakSelf.dataItems addObject:[Product createProductByDictionary:obj]];
                }];
                [[NSManagedObjectContext MR_defaultContext] MR_saveToPersistentStoreWithCompletion:^(BOOL contextDidSave, NSError *error) {
                    if (error) {
                        return ;
                    }
                    [curTableView reloadData];
                    [weakSelf checkoutData];
                }];
            }];
        }
    }];
````

And it crashed in the ````NSManagedObject+MagicalRecord.h```` line284.
What's the matter with my code ?

**Comment by tonyarnold** [comment]
Hi @seanLee, what's the crash? Can you post the details and backtrace from the crash here so I can help diagnose the issue? Thanks!

**Comment by seanLee** [comment]
I would like to find the crash,but there's nothing print in the console.And I found  something maybe help you,that's:
````NSManagedObjectContext __Multithreading_Violation_AllThatIsLeftToUsIsHonor__````
and 
````EXC_BAD_INSTRUCTION (code=EXC_I386_INVOP,subcode=0x0)````
May it make memory leak when I do something in the  ````saveWithBlock````,but I really don't known what's the matter.

**Comment by Alydyn** [comment]
That means that you are accessing NSManagedObjects from the wrong queue.  You need to make sure you are handling threading correctly.

**Comment by Alydyn** [comment]
Make sure you [turn on concurrency debugging](http://oleb.net/blog/2014/06/core-data-concurrency-debugging/)

@tonyarnold Any way we can get turning on concurrency debugging put in the Readme or somewhere?  It seems like concurrency is constantly a source of new issues.

**Comment by seanLee** [comment]
@Alydyn  I know what's ur meaning,and I have turned on concurrency debugging.Actually,I know the error is caused about the queue.But for my pool experience,I don't how to handle this problem.

**Comment by Alydyn** [comment]
If you have concurrency debugging turned on then when it crashes with the `AllThatIsLeftToUsIsHonor` exception, you can browse the stack trace to see exactly where the illegal access occurred.

**Comment by seanLee** [comment]
@Alydyn  OK,I will try to find what made this error.

**Comment by hardikdevios** [comment]
@seanLee can you let us know which ***Xcode*** version you are using ?

**Comment by seanLee** [comment]
@hardikdevios yeah.I use the Version 6.4.It's the newest version.

**Comment by seanLee** [comment]
@hardikdevios And now I run the code that had made crash,It's OK,and even not crash one time.What a confusing situation.

**Comment by seanLee** [comment]
@hardikdevios It does not crash on the simulator but on the real machine this time.
