### ISSUE TITLE
-deleteObject: requires na non-nil argument

### ISSUE THREAD

**Issue by ps-sstumpfl** [magicalpanda/MagicalRecord#1071]
MR_deleteEntityInContext might fail and crash the App if the ManagedObject doesn't exist anymore.

    -deleteObject: requires na non-nil argument
    *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: ''-deleteObject:         requires na non-nil argument"

I think this could be avoided by using the same process as MR_inContext does?

**Comment by wongzigii** [comment]
Hey @ps-sstumpfl  I met this problem today. Have you find out any idea what is going wrong here?

**Comment by wongzigii** [comment]
My app crash on this line:
https://github.com/magicalpanda/MagicalRecord/blob/master/MagicalRecord/Categories/NSManagedObject/NSManagedObject%2BMagicalRecord.m#L225

It looks like that the NSManagedObject in context could not be found.

**Comment by ps-sstumpfl** [comment]
@wongzigii MR_deleteEntitiyInContext() doesn't check if the ManagedObject it's going to delete is nil. It might be the best checking or nil before deleting the object.

**Comment by taher-mosbah** [comment]
+1 Got the same problem in Crashlytics logs

**Comment by wongzigii** [comment]
@ps-sstumpfl 

    if (inContext) {
      [context deleteObject:inContext];
    }

**Comment by tonyarnold** [comment]
This is fixed by fa42e89b4a00a9d5e8eab88c5520b6a1f1b8456d, which is in v2.3.1 and later.
