### ISSUE TITLE
Nullability

### ISSUE THREAD

**Issue by florianbuerger** [magicalpanda/MagicalRecord#1078]
One of the [latests commits on the 3.0 branch](https://github.com/magicalpanda/MagicalRecord/commit/b0e21d1924aca6ac2ed7357a51ed605439258ef0) introduced nullability annotations for most of the classes. 

Problem is, that is Xcode 7 specific syntax. It won't compile when using Xcode 6. The Xcode 6 syntax for nullability was different (which is such a bad choice btw). I know Xcode 7 is around the corner but not all projects out there can easily upgrade to the iOS 9 SDK right away. 

At the moment I have no good idea how to solve this problem. Until then, I'll use the pod version from a previous commit.

**Comment by magicalpandatest** [comment]
Ah, thanks for the reminder. 
I think we can do some MR specific toggling of syntax. Ill see what I can do.

**Comment by tonyarnold** [comment]
Check the 2.3 sources. There's an Xcode 7 comparability header there that was released with 2.3.0.

**Comment by florianbuerger** [comment]
I re-read [Apples post on nullability](https://developer.apple.com/swift/blog/?id=25). The old style macro `__nullable` & `__nonnull` work on both platforms. 

I've create #1079 for this. Code compiles fine on Xcode 6.4 & Xcode 7.0 Beta 6
