### ISSUE TITLE
 Remote branch v2.3.0 not found in upstream origin

### ISSUE THREAD

**Issue by pablobfs** [magicalpanda/MagicalRecord#1096]
Hi, i´m not being able to work with cocoa pods, a couple of week ago it was working perfectly but now the remote branch is not responding.

"fatal: Remote branch v2.3.0 not found in upstream origin"

Is anybody else having this issue?

Thanks!

**Comment by pablobfs** [comment]
Hi, i´m not being able to work with cocoa pods, a couple of week ago it was working perfectly but now the remote branch is not responding.

"fatal: Remote branch v2.3.0 not found in upstream origin"

Is anybody else having this issue?

Thanks!

**Comment by tonyarnold** [comment]
I don't think we ever had a `v2.3.0` branch. There's a tag — and that's still there?
