### ISSUE TITLE
warnings

### ISSUE THREAD

**Issue by danipralea** [magicalpanda/MagicalRecord#1117]
These are the warnings that appear in Xcode 7.1, iOS SDK 9.1 :

<img width="1264" alt="screenshot 2015-10-30 23 48 42" src="https://cloud.githubusercontent.com/assets/768893/10858859/de906492-7f60-11e5-821a-b6bdc89dc5f2.png">

**Comment by Coeur** [comment]
I can't reproduce your issue: `shouldImport:` is defined in `NSManagedObject+MagicalDataImport.h` which is imported at the top of `NSManagedObject+MagicalDataImport.m`.
