### ISSUE TITLE
MR_observeContextOnMainThread deadlocks the main thread

### ISSUE THREAD

**Issue by pronebird** [magicalpanda/MagicalRecord#1123]
If you set up a main queue context, change objects in it and save it, you get the app deadlocked.

```objc
NSManagedObjectContext *rootContext = [NSManagedObjectContext MR_rootSavingContext];
self.context = [NSManagedObjectContext MR_newMainQueueContext];
[self.context setParentContext:rootContext];
[self.context MR_observeContextOnMainThread:rootContext];
```

This is bullshit. 

1. Root context does not rely on `MR_observeContextOnMainThread` implementation at all. 
2. Root context uses `dispatch_async` to merge changes to default context, while `MR_observeContextOnMainThread` uses `performSelectorOnMainThread` with `waitUntilDone = YES`. 

This is crazy. 

These methods should be fixed and united with Root context implementation or removed from MagicalRecord because they are harmful.

**Comment by tonyarnold** [comment]
> This is bullshit

Thanks!
