### ISSUE TITLE
Jailbroken and MagicalRecord

### ISSUE THREAD

**Issue by marinotws** [magicalpanda/MagicalRecord#1126]
Some users with iphone Jailbroken complains malfunctioning on my app database problems, someone happened ? possible?

thanks

**Comment by tonyarnold** [comment]
It shouldn't make any difference, to be honest. Unless the user who has jailbroken their device has installed something that interferes with MagicalRecord, I don't see how it would operate differently. Then again, I don't jailbreak my devices so I'm really not sure. 

If you can identify a specific issue or error, I'm happy to have a look but honestly I'm not sure it's in anyone's best interests to support jailbroken devices.
