### ISSUE TITLE
tvOS pod?

### ISSUE THREAD

**Issue by f1nality** [magicalpanda/MagicalRecord#1142]
Hello,

Can tvOS support be added to podspec?

**Comment by nidom** [comment]
same problem...

**Comment by miradesne** [comment]
Can watchOS support be added to podspec?

**Comment by tonyarnold** [comment]
Until we've removed any use of `NSConfinementConcurrencyType`, I don't believe we can compile a tvOS binary (same for watchOS, I would assume). 

I've started this work as part of MagicalRecord version 3.0

**Comment by miradesne** [comment]
@tonyarnold Thanks! :)

**Comment by rsanchezsaez** [comment]
@tonyarnold That's great! Any approximate ETA?

We're trying to make a lightweight version of our app for Apple TV, and not being able to use Magical Record is a major headache. ;)

**Comment by Coeur** [comment]
I've added support for tvOS and watchOS on master branch / MagicalRecord 2.4.0.
