### ISSUE TITLE
saving always is failure 

### ISSUE THREAD

**Issue by michaelmou** [magicalpanda/MagicalRecord#1156]
```swift
let identifier = application.beginBackgroundTaskWithExpirationHandler {
            
        }

        MagicalRecord.saveWithBlock({ (context) -> Void in
            
            context.MR_saveWithOptions(MRSaveOptions.SynchronouslyExceptRootContext){ (succeed, error) -> Void in
                
                if error != nil{
                    print("error focus on saving persistenStore:\(error)")
                }
                application.endBackgroundTask(identifier)
                
            }

        })
```

**Comment by hardikdevios** [comment]
@michaelmou Any Error is printing ?

**Comment by michaelmou** [comment]
anything is ok, but the parameter of succeed is false.

**Comment by tonyarnold** [comment]
This is probably the result of a long running error in our logic. The BOOL was not supposed to be an indication of an error occurring — a save might not occur (and thus return `NO`) if there are no changes to save. 

I know, it's a debatable choice. I should verify what Core Data does in this circumstance and copy that.

**Comment by tonyarnold** [comment]
Yeah, so basically we're just passing back what NSManagedObjectContext gives us. If you try to save a context with no changes, the save result is `NO`. I don't think we should be going against what the framework does here, but I'm happy to consider arguments for it.
