### ISSUE TITLE
Shorthand methods - possible typo?

### ISSUE THREAD

**Issue by ashaman** [magicalpanda/MagicalRecord#1175]
Hi there,
I'm using MagicalRecord v.2.3.2 from master (with CocoaLumberjack support) and I'm experiencing some issues with shorthand instance methods, like `-inContext` (I receive `unrecognized selector` exceptions). At the same moment, shorthand class methods are resolved correctly.

After the debugging, it seems to me that there's a typo in _MagicalRecord+ShorthandMethods.m, line 93_. Adding "!", like in the example below, resolved all shorthand issues for me:

 `!([originalSelectorString hasPrefix:@"_"] || [originalSelectorString hasPrefix:@"init"]))`

I've searched for similar issues, but found nothing like this.

**Comment by tonyarnold** [comment]
I can't remember why these checks are even in here. @casademora do you have any recollection about why we would explicitly include or exclude class methods starting with `_` or `init`? In theory, this method should only target methods starting with `MR_`.

**Comment by Coeur** [comment]
Fixed in a4c59b55c9be1093812818330705806e96d7a654
