### ISSUE TITLE
MagicalRecord 2.3.2 with carthage, iTunes connect error

### ISSUE THREAD

**Issue by mmdumi** [magicalpanda/MagicalRecord#1180]
Hi guys,
I don't know exactly how carthage works internally but recently when I update carthage with magical record it's downloading the framework directly:

`*** Downloading MagicalRecord.framework binary at "MagicalRecord v2.3.2"`
For some reason the downloaded MagicalRecord.framework is built agains ios 9.3 and this causes issues on upload:

`[11:34:18]: Return status of iTunes Transporter was 1: ERROR ITMS-90512: "Invalid sdk value. The value provided for the sdk portion of LC_VERSION_MIN_IPHONEOS in QuickWins QA.app/Frameworks/MagicalRecord.framework/MagicalRecord is 9.3 which is greater than the maximum allowed value of 9.2."`

**Comment by mmdumi** [comment]
Ok after reading more about Carthage I found that you guys linked the prebuilt framework to the 2.3.2 release but that framework is built agains a iOS 9.3
Thanks for your work.

**Comment by tonyarnold** [comment]
Yeah, I made a horrible mistake (it was late!). I've automated the Carthage binary build and deployment now, so v2.3.3 should be built correctly against Xcode 7.2. Let me know if this doesn't fix the issue — and thanks for reporting the problem!

**Comment by mmdumi** [comment]
It's all good. Thanks again for your work.

**Comment by murthy8** [comment]
@mmdumi actually i have some of the doubts.i am integrating Magical Record 2.3.2 sdk in my application. now magical record 2.3.3 sdk released in one month back. so i was checking magical record 2.3.3 documentation. but i can't get any proper information on what are the changes from magical record 2.3.2 sdk to magical record 2.3.3 sdk. so please guide me what are the changes or what are the differences in magical record 2.3.2 to magical record 2.3.3.. i am refer this link. "https://github.com/magicalpanda/MagicalRecord/releases"

**Comment by mmdumi** [comment]
@murthy8 Only the Info.plist got changed in MagicalRecord.framework 
Version 2.3.2 was built with a beta sdk and this caused an issue to be triggered when trying to upload an app to itunes. 
Version 2.3.3 is compiled with the latest release (non-beta) sdk.

**Comment by murthy8** [comment]
@mmdumi  thanks for your response. Then what are the changes in info.plist plz tell me

**Comment by mmdumi** [comment]
<key>DTPlatformVersion</key>
<string>9.3</string>

**Comment by murthy8** [comment]
@mmdumi then i have another doubt. you told me only the info.plist file changed.. so why we need to integrate MagicalRecordSDK. 2.3.3??

**Comment by murthy8** [comment]
@mmdumi  Magical Record idk 2.3.3 is not provided by cocoa pods. so how can integrate my code. actually i was integrated magical record 2.3.2 sdk through cocoa pods. so now can i delete magical record 2.3.2, and magical record 2.3.3 sdk download and drop into my Xcode project?? this is right way?

**Comment by murthy8** [comment]
@mmdumi  i need your guidance. can i integrate magical record 2.3.3 in my xcode?? this is stable release or still having any issues.? please give me your suggestion

**Comment by mmdumi** [comment]
@murthy8 Yes you can integrate it. It's a stable release.

**Comment by murthy8** [comment]
@mmdumi but actually magical record  2.3.3 is not able to integrate from cocoa pods right?? why because cocoapods does not provide 2.3.3 version. so can i integrate directly means. download and drag and drop into my project?

**Comment by murthy8** [comment]
@mmdumi  i have one more doubt. plz give me answer.. this is my last doubt. what is the difference between Magical Record 2.3.1 and Magical Record 2.3.3.. why we need to integrate magical record 2.3.3. is there any advantages for this? i mean performance wise e.t.c plz give me the answer this is my last doubt.

**Comment by murthy8** [comment]
@mmdumi  hi sir. very good morning.. i am importing magicalrecord sdk 2.3.3 in my project.. means copy the magicalrecord items in my project. i am not using cocoapods.. i got one issue.. i.e. "MagicalRecord/MagicalRecordXcode7CompatibilityMacros.h file not found in xcode7" how to solve the issue??

**Comment by murthy8** [comment]
@mmdumi the issue is getting from "NSAttributeDescription+MagicalDataImport.h" file...

**Comment by murthy8** [comment]
@mmdumi  i was integrating Magical Record sdk 2.3.2.. it is integrated successfully. but i have some errors. i.e. "mr_contextforcurrentthread deprecated in magicalrecord 3.0".. so how to fix this issue. plz guide me

**Comment by murthy8** [comment]
@mmdumi   last week i integrated Magical Record 2.3.2 beta version.. but i was tried to integrate Magical Record 2.3.3 latest version. but i got failure.. so finally i integrated Magical Record 2.3.2 beta sdk. but now i need to integrate Magical Record 2.3.3 sdk.. so will you please guide me how to integrate Magical Record 2.3.3 sdk without facing any issue... plz give me response.. it is on demand.. Thanks in advance... plz give me your guidance.. it is on demand to update.. Thank you.....

**Comment by murthy8** [comment]
@tonyarnold  last week i integrated Magical Record 2.3.2 beta version.. but i was tried to integrate Magical Record 2.3.3 latest version. but i got failure.. so finally i integrated Magical Record 2.3.2 beta sdk. but now i need to integrate Magical Record 2.3.3 sdk.. so will you please guide me how to integrate Magical Record 2.3.3 sdk without facing any issue... plz give me response.. it is on demand.. Thanks in advance... plz give me your guidance.. it is on demand to update.. Thank you.....
