### ISSUE TITLE
is There any method support paging? 

### ISSUE THREAD

**Issue by guoshencheng** [magicalpanda/MagicalRecord#1193]
###### example
`If I saved 100 records, i may just need pick up records form 90 ~ 100 or 80 ~ 90`

 #183 Just solved a problem for picking up records form 90~100 or 80~100

**Comment by danielgalasko** [comment]
I think you are looking for info in the wrong place and should instead consult Core Data documentation. It looks like you are looking for either NSFetchRequest's `fetchBatchSize` property or `fetchOffset`. Read more [here](https://developer.apple.com/library/mac/documentation/Cocoa/Reference/CoreDataFramework/Classes/NSFetchRequest_Class/)

**Comment by guoshencheng** [comment]
@danielgalasko thanks, I have found the solution but forgot to close the issue, thanks for your reply again!

**Comment by guoshencheng** [comment]
thanks, I have found the solution, thanks for your reply again!  and can I close the issue?

**Comment by guoshencheng** [comment]
@danielgalasko  okey.. I find the close button~~~
