### ISSUE TITLE
Error installing on OS X project via Cocoapods

### ISSUE THREAD

**Issue by ghost** [magicalpanda/MagicalRecord#1197]
I get this after adding to the podfile, installing and trying to build;

`Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_DDLog", referenced from:
      objc-class-ref in MagicalRecord+ErrorHandling.o
      objc-class-ref in NSEntityDescription+MagicalDataImport.o
      objc-class-ref in NSManagedObject+MagicalDataImport.o
      objc-class-ref in NSManagedObject+MagicalRecord.o
      objc-class-ref in NSManagedObjectContext+MagicalObserving.o
      objc-class-ref in NSManagedObjectContext+MagicalRecord.o
      objc-class-ref in NSManagedObjectContext+MagicalSaves.o
      ...
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)`

**Comment by Coeur** [comment]
You did not show us your Podfile. No such issue for me.
