### ISSUE TITLE
Build fail on xcode7 due to pragma marks in macro

### ISSUE THREAD

**Issue by TerjeLonoy** [magicalpanda/MagicalRecord#1205]
As title states, the build fails due to pragma marks being defined in a macro.

This occurs at file: NSManagedObjectContext+MagicalRecord.m
Lines: 248-251

**Comment by Coeur** [comment]
You mean `#pragma clang diagnostic push`? This is a perfectly fine pragma. And Travis CI is happy with Xcode 7.3 and Xcode 10.1: https://travis-ci.org/magicalpanda/MagicalRecord/builds/539138993
