### ISSUE TITLE
Errors with Swift 2.2 / Xcode 7.3

### ISSUE THREAD

**Issue by Dschee** [magicalpanda/MagicalRecord#1211]
Hi, I just tried to install the latest commit of the release/3.0 branch via Carthage but I got the following errors:

```
Carthage/Checkouts/MagicalRecord/Library/Categories/CoreData/Import/MagicalImportFunctions.m:89:72: error: implicit conversion increases floating-point precision: 'float' to 'CGFloat' (aka 'double') [-Werror,-Wdouble-promotion]
```

I didn't change anything in code / dependency version but I updated Xcode which has now Swift 2.2 integrated and may have added some more requirements so I guess this is a compatibility problem that we need to fix.

**Comment by Coeur** [comment]
Fixed in 14a5935b9852d285898555ebb405084077a362e5
