### ISSUE TITLE
编译报错？怎么运行呢

### ISSUE THREAD

**Issue by hhb19900618** [magicalpanda/MagicalRecord#1229]

**Comment by hei9gag** [comment]
Please translate your request to English please. I don't think the creator can read Chinese..

**Comment by casademora** [comment]
more importantly, this ticket is simply asking how it works without trying to run the docs through a translator...which is how I read this ticket. Sorry, this is a read the manual problem. There are numerous docs and examples on the internet showing how to get started with MagicalRecord.
