### ISSUE TITLE
Export database to JSON?

### ISSUE THREAD

**Issue by jerryga** [magicalpanda/MagicalRecord#1234]
How to export core data to JSON?

**Comment by lolgear** [comment]
uncleared. choose option that you mean by "core data to json":
- export entity to json 
- export table to json
- export database to json

**Comment by jerryga** [comment]
export database to json.
Thank you.

**Comment by Coeur** [comment]
One way to do it:
1. Convert your data to object instances.
2. Convert your object instances to Foundation objects (Dictionaries, Arrays, String, ...)
3. Convert your Foundation objects to JSON with [NSJSONSerialization](https://developer.apple.com/documentation/foundation/nsjsonserialization).

MagicalRecord only supports step 1.
