### ISSUE TITLE
Can not install 2.3.2 version with last cocoa pods update

### ISSUE THREAD

**Issue by bizibizi** [magicalpanda/MagicalRecord#1241]
Always have an error that can not find Magical Record files in Bridging header

**Comment by bizibizi** [comment]
I tried all combination of imports but its not working

**Comment by pjryan93** [comment]
Same problem, did you try downgrading cocoapods?

**Comment by WERUreo** [comment]
I was also having this problem when trying to build MagicalRecord 2.3.2 with the latest version of Cocoapods (v1.0.1).  Downgrading Cocoapods back to v0.39.0 helps, but you'll need to make sure you remove the newer version of Cocoapods first, install 0.39.0, and run 'pod install'.  It would probably also help to delete the Podfile.lock as well as the Pods directory just to be sure it's not trying to use a newer version of Cocoapods.

Apparently there is a version 3.0 of MagicalRecord that does build with the latest Cocoapods, but that doesn't seem to be getting much support (last update 5 months ago).

**Comment by bizibizi** [comment]
yes, I am using 

pod 'MagicalRecord/Shorthand'

with previous version

**Comment by sjmn** [comment]
try adding:

`${TARGET_BUILD_DIR}/Pods/MagicalRecord`

to framework search paths.  Clean, build.  For me after this worked, I could remove the above from framework search paths.  YMMV.

**Comment by Coeur** [comment]
I've never had issues with CocoaPods 1.6.2. I'll consider that problem solved. Otherwise, please specify your version of CocoaPods (and note that I'll only support CocoaPods 1.7.2+ from now on) and your Podfile content.
