### ISSUE TITLE
Swift 3.0 .save

### ISSUE THREAD

**Issue by ignotusverum** [magicalpanda/MagicalRecord#1260]
After migrating project to Swift 3.0, i'm having following issues with .save method:

```
// Previously .saveWithBlock
    MagicalRecord.save { context in 
    // Save some changes here
 }
```

"Ambiguous use of 'save' ", any ideas how to fix it ?

Thanks

**Comment by jayDLabs** [comment]
Yes, just add "(" and ")" around your block :
`         MagicalRecord.save({ (context) in
// Save some changes here
        })`
