### ISSUE TITLE
Use CocoaLumberjack 3.0.0

### ISSUE THREAD

**Issue by LaurentiuUngur** [magicalpanda/MagicalRecord#1262]
Update `CocoaLumberjack` subspec to:
`s.subspec 'CocoaLumberjack' do |sp|
    sp.dependency 'CocoaLumberjack', '~> 3.0'
    sp.dependency 'MagicalRecord/Core'
  end`

**Comment by Coeur** [comment]
Agreed. Will be in next release (or at least, on master branch, if you do `pod 'MagicalRecord/CocoaLumberjack', :git => 'https://github.com/magicalpanda/MagicalRecord'`).
