### ISSUE TITLE
MagicalRecord database for multiple users

### ISSUE THREAD

**Issue by mihaipuscasimprezzio** [magicalpanda/MagicalRecord#1269]
Hi, is there a way to set a new database for each user, based on their id to create different files, so when the app launches the store for the current logged in user?

**Comment by vitalys** [comment]
It's easy. Create unique DB name for your user and use this name in setup method:

`[MagicalRecord setupCoreDataStackWithAutoMigratingSqliteStoreNamed: dbName]`

**Comment by mihaipuscasimprezzio** [comment]
Hi,

Ok, and in order to change the DB for the new user should i call 'cleanUp' before 'setupCoreDataStackWithAutoMigratingSqliteStoreNamed' ?

Thanks

On 25 Oct 2016, at 19:57, Vitaly S. <notifications@github.com<mailto:notifications@github.com>> wrote:


It's easy. Create unique DB name for your user and use this name in setup method:


This message may be subject to nondisclosure, copyright and privacy policy. If you have received this message in error, please notify the sender

**Comment by vitalys** [comment]
You have to call `cleanUp` before setup new core data stack.
