### ISSUE TITLE
iCloud support - need help

### ISSUE THREAD

**Issue by unpaq** [magicalpanda/MagicalRecord#127]
I am using MagicalRecord in my project. It has been working fine so far with a SQLite store. But now I am trying to "upgrade" to iCloud to have sync between my iPhone and iPad versions.

But it is not working as I expected. The app still works the same - data is getting saved and read back, but it is not saved in iCloud as I would expect.

The only change I have made is in the MagicalRecord setup.

Before:
[MagicalRecordHelpers setupCoreDataStackWithAutoMigratingSqliteStoreNamed:@"hdhomerun.sqlite"];

After:
[MagicalRecordHelpers setupCoreDataStackWithiCloudContainer:@"AAAAAAAAAA.com.unpaq.hdhomerun" localStoreNamed:@"hdhomerun_local"];

The AAAAA's are not AAAAA's in the code, but my private ID from developer profile.

I can see in the output log that iCloud is detected and no errors occur. I also tried stepping through the code and it all looks fine.

What am I missing? Do I need to listen to some event? I have not been able to find an example of how to use MagicalRecord with iCloud.

**Comment by lassebunk** [comment]
I haven't read the entire thread but found it because I was experiencing similar symptoms.
After changing this:
```swift
MagicalRecord.setupCoreDataStackWithiCloudContainer("some-id", localStoreNamed: "AppName")
```
to this:
```swift
MagicalRecord.setupCoreDataStackWithiCloudContainer("some-id", contentNameKey: "AppNameData", localStoreNamed: "AppName", cloudStorePathComponent: nil)
```
I got iCloud syncing working between my devices. Hopes this helps.
