### ISSUE TITLE
Getting Crash - Invalid pointer dequeued from free list *** set a breakpoint in malloc_error_break to debug

### ISSUE THREAD

**Issue by abhisheksingh1** [magicalpanda/MagicalRecord#1278]
I'm trying to make the MagicalRecord MR_importValuesForKeysWithObject method - 

Xcode 8.1, Swift 2.3 and having relationship in my entity.

Crashes here with EXC_BAD_ACCESS:
https://github.com/magicalpanda/MagicalRecord/blob/42ddbae5ebc7518ab4bcb009aae8e5f6d036f7bf/MagicalRecord/Categories/NSManagedObject/NSManagedObject%2BMagicalRecord.m#L54

**Comment by Coeur** [comment]
- `MR_importValuesForKeysWithObject:` is called more than 50 times in our unit tests.
- The line `[context executeFetchRequest:request error:&error]` is called more than 30 times in our unit tests.

To me, this issue currently lacks a [Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example).
