### ISSUE TITLE
NSUnknownKeyException - this class is not key value coding-compliant for the key length.

### ISSUE THREAD

**Issue by kjmaior** [magicalpanda/MagicalRecord#1279]
Performing a MR_findAllSortedBy: ascending: withPredicate is resulting in application crash because of NSUnknonwKeyException.  The very odd part is the same exact predicate works in one instance but causes the crash in another.  An example of one such predicate is as follows:

(version == 10 AND riderClass == "A") AND eastOffPeak == 1 AND (restrictToDays == nil OR restrictToDays.length <= 0 OR restrictToDays == 0 OR restrictToDays & 2 == 2) AND (restrictToTrain == nil OR restrictToTrain.length <= 0 OR restrictToTrain == "1622") AND (restrictToJob == nil OR restrictToJob.length <= 0 OR restrictToJob == "815") AND soldOnboard == 1 AND (identifier != 9022 AND identifier != 5005)

Any other information you think would be helpful please let me know.  Unfortunately I cannot recreate and my crashlytics report doesn't have magicalrecord stack trace because of missing dysym.

Thanks!

**Comment by Coeur** [comment]
I'm sorry, but it's too much time consuming to investigate on issues without a [Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example).
