### ISSUE TITLE
MagicalRecord/MagicalRecordShorthandMethodAliases.h not found in v2.3.2

### ISSUE THREAD

**Issue by RenugaMohan** [magicalpanda/MagicalRecord#1282]
In my pods, MagicalRecord/MagicalRecordShorthandMethodAliases.h is missing. Im using MagicalRecord version 2.3.2

**Comment by Coeur** [comment]
It is provided as a separate subspec, so you need to write this in your Podfile:
```ruby
pod 'MagicalRecord'
pod 'MagicalRecord/ShorthandMethodAliases'
```
