### ISSUE TITLE
Use of undefined identifier 'LOG_ASYNC_ENABLED' 

### ISSUE THREAD

**Issue by philipacrowe** [magicalpanda/MagicalRecord#1283]
Hello, I've inherited a project that wont build in iOS 10. The pod that has a problem is MagicalRecord:

pod "MagicalRecord/CocoaLumberjack", :git => "https://github.com/magicalpanda/MagicalRecord.git"

When trying to build all references to MRLogWarn is giving the error: Use of undefined identifier 'LOG_ASYNC_ENABLED'. Project is Objective C.

**Comment by teixeiras** [comment]
same issue here

**Comment by martinjkelly** [comment]
Any updates on this issue? I'm getting the same

**Comment by Coeur** [comment]
If you look at the podspec that you're integrating, you'd notice:
https://github.com/magicalpanda/MagicalRecord/blob/13033b8814e9e518ae867818c1325f93801305ae/MagicalRecord.podspec#L30-L33

Which means that all it does is the same as writing:
```ruby
pod 'CocoaLumberjack', '~> 2.0'
pod 'MagicalRecord'
```

So you're probably facing an issue with CocoaLumberjack 2.x.
Note that we've updated to CocoaLumberjack 3.x in MagicalRecord 2.4.0, and that identifier certainly exists there: https://github.com/CocoaLumberjack/CocoaLumberjack/search?q=LOG_ASYNC_ENABLED&unscoped_q=LOG_ASYNC_ENABLED

So please try MagicalRecord master branch or 2.4.0 once released.
