### ISSUE TITLE
Update records in swift 3

### ISSUE THREAD

**Issue by ShahVivek** [magicalpanda/MagicalRecord#1298]
I want to add/update/delete records using MagicalRecord in swift 3.
I am able to add and fetch records. But I don't know how can I update multiple records.
I am fetching records using below method

`mr_findAll(with searchTerm: NSPredicate?)`

Can anyone help me that , how can I update this records?

**Comment by ryancarlson** [comment]
I can think of a couple different ways:

````swift
MagicalRecord.save(blockAndWait: { (context) 
  let predicate = NSPredicate( ... )
  let models = MyModel.mr_find(with: predicate, in: context)
  
  for model in models {
    model.foo = "bar"
  }
}
````
or:
````swift
let context = NSManagedObjectContext.mr_default()
let predicate = NSPredicate( ... )
let models = MyModel.mr_findAll(with: predicate, in: context)
  
for model in models {
  model.foo = "bar"
}
context.mr_saveToPersistentStoreAndWait()
````

Of course you don't have to use the methods that block until saving if you don't want to. Hope this helps!

**Comment by vishaldeshai** [comment]
Plz use same code as you used for add record but use attributes with primary key
for e.g take a key like 'ID' as a primary.
when you save then record will be updated.

**Comment by Coeur** [comment]
Documentation has been recently updated to include Swift code.
- to fetch records: https://github.com/magicalpanda/MagicalRecord/blob/master/Docs/Fetching-Entities.md
- to save your changes: https://github.com/magicalpanda/MagicalRecord/blob/master/Docs/Saving-Entities.md

Also, thank you @ryancarlson for your great examples.
