### ISSUE TITLE
Crash when saving 

### ISSUE THREAD

**Issue by antonbremer** [magicalpanda/MagicalRecord#1315]
When I call mr_saveToPersistentStoreAndWait() I am getting weird errors in some cases.
I cannot find the issue here, been looking at it for a long time now. 
I was hoping somebody here could point me into the right direction..

Verbose logging gives me the following:
2017-08-24 12:12:55.166063+0100 trustedfamily-ios[35906:2870101] [error] error: oid = 0xd0000000054c0020 <x-coredata://79D4E1A0-5016-4D96-84B0-4AF1002799A4/Document/p339> [oid class] = _NSCoreDataTaggedObjectID expecting entity Survey
CoreData: error: oid = 0xd0000000054c0020 <x-coredata://79D4E1A0-5016-4D96-84B0-4AF1002799A4/Document/p339> [oid class] = _NSCoreDataTaggedObjectID expecting entity Survey

There is three entities in my Object model that are involved in this crashed.

There is an entity event, which is more or less a calendar event.
In this event is a 1 to 1 relation to an entity Survey
Also to this event you can attach multiple documents (entity Document)
The entities Document and Survey have no direct relation to each other

Nevertheless the error says something about the entity Document is expecting entity Survey.
I am not understanding this error and don't know at this point how to solve it.

Cheers,
Anton

**Comment by vishaldeshai** [comment]
Can you put code snipped??
