### ISSUE TITLE
Request a different file protection level

### ISSUE THREAD

**Issue by dudeinthemirror** [magicalpanda/MagicalRecord#1323]
Is there a way to pass an `options` dictionary to `setupCoreDataStackWithAutoMigratingSqliteStoreNamed` ?
In general, is there a way to request a different file protection level ?

For example:
````
NSDictionary *storeOptions = @{NSPersistentStoreFileProtectionKey  : NSFileProtectionComplete};
[MagicalRecord setupCoreDataStackWithAutoMigratingSqliteStoreNamed:@"my_db" options: storeOptions];
````

**Comment by Coeur** [comment]
Feature is being added today. See #1364.
