### ISSUE TITLE
Swift 4.1 - error thread

### ISSUE THREAD

**Issue by daiwud** [magicalpanda/MagicalRecord#1328]
I get an error in the method

+ (id) MR_importFromObject: (id) objectData inContext: (NSManagedObjectContext *) context;

 [context performBlockAndWait:^{ -------------- ERROR THREED

**Comment by Coeur** [comment]
Your issue is lacking a [Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example).

I've been using MagicalRecord with Swift 3.0, 4.0, 4.2 and 5.0 without issues.
