### ISSUE TITLE
`git_release_version` in `set_version_information.sh` make app upload to AppStore Failed

### ISSUE THREAD

**Issue by GrayLand119** [magicalpanda/MagicalRecord#1332]
When I upload my app to AppStore, I got this error below:

ERROR ITMS-90060: "This bundle is invalid. The value for key CFBundleShortVersionString '842796f76d92c4374707aa26c3d24af87d54ae51' in the Info.plist file must be a period-separated list of at most three non-negative integers."

and I checked my git log, I found the same string `842796f76d92c4374707aa26c3d24af87d54ae51`.

```shell
grayland$ git log
commit 842796f76d92c4374707aa26c3d24af87d54ae51
```

and I found that the same string in:
`<ProjectDir>/Carthage/Build/MagicalRecord/MagicalRecord.framework/Info.plist`.

Here is the content in Info.plist:

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<string>842796f76d92c4374707aa26c3d24af87d54ae51</string>
</plist>
```

It set the BundleVersion auto automatically without checking the format!

It's very difficult to find this error... cuz You can't search and find this string in anywhere!

The the problem Shell Code In:
`<ProjectDir>/Carthage/Checkouts/MagicalRecord/Support/Scripts/set_version_information.sh`

**Comment by Coeur** [comment]
Such commit doesn't exist on this repository: https://github.com/magicalpanda/MagicalRecord/commit/842796f76d92c4374707aa26c3d24af87d54ae51

**Comment by Coeur** [comment]
No answer, closing.
