### ISSUE TITLE
App crashed on setValue for attribute type binary data

### ISSUE THREAD

**Issue by Instadex** [magicalpanda/MagicalRecord#1340]
After converting our code base to Swift 4.2 we were getting crash when setting value for attributes of type "binary data". I have updated the attributes to "Transformable type" but it is not inserting the data in DB.

Error when the data type was binary data: "desired type NSData given type __NSDictionary error"

**Comment by Coeur** [comment]
This is not enough for us to analyze the issue: you'd need [a Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example).

For me, no issue with Transformable types using Swift 5 and MagicalRecord (master branch), so I'll close that issue until more useful details are provided (you can also make a Pull Request).
