### ISSUE TITLE
CFBundleShortVersionString is missing when Framework gets compiled from sources

### ISSUE THREAD

**Issue by pertau** [magicalpanda/MagicalRecord#1373]
When Carthage needs to build from sources, the CFBundleShortVersionString is missing. 

In our case we were reaching the API rate limit for Github on our CI, so it skipped downloading the binary and just compiled from sources.

**Comment by Coeur** [comment]
Please provide a pull request.

**Comment by pertau** [comment]
It happened on our CI which used carthage, configured in cartfile use v2.3.3.

Lets see what happens if I set up carthage to build from master and then verify if it happens again when I choose tag v2.3.3

**Comment by pertau** [comment]
It`s interesting, i can't reproduce it. will close this issue.
