### ISSUE TITLE
MR_inContext returns nil for just-created (and saved) object

### ISSUE THREAD

**Issue by justinrosenthal** [magicalpanda/MagicalRecord#184]
I have a simple test app, there are two buttons: "Create" and "Modify"

When I hit "Create", I am creating an entity on the main thread (in the default context) and saving it.  Inspecting the sqlite file at this point in the execution shows that the object has indeed been persisted.

When I hit "Modify" I find the just-created object (works fine), and then i attempt a saveInBackgroundWithBlock... where the first thing it does is try to get the object we just found, but in the local context via MR_inContext:localContext but it always returns nil.

Seems possible that I'm doing something stupid, but would love to know what it is or if this is actually a bug.

``` objective-c
- (void)create {
    assert([NSThread isMainThread]);
    TestModel *model = [TestModel MR_createEntity];
    model.color = [NSNumber numberWithInt:0];
    [[NSManagedObjectContext MR_defaultContext] MR_save];
}

- (void)modify {
    TestModel *model = [TestModel MR_findFirstByAttribute:@"color" withValue:[NSNumber numberWithInt:0]];
    assert(model != nil);

    [MagicalRecord saveInBackgroundWithBlock:^(NSManagedObjectContext *localContext) {
        TestModel *localModel = [model MR_inContext:localContext];
        assert(localModel != nil);  // <---- This assertion fails

        localModel.color = [NSNumber numberWithInt:(arc4random() * 0xffffff)];
        [localContext MR_saveNestedContexts];
    }];
}
```

**Comment by sryze** [comment]
I think I'm experiencing the same issue with latest MagicalRecord.

I create a child context with `MR_context` and after adding an object to that context I pass it to a method that calls `MR_inContext against a local context inside a save block like this:

```
[MagicalRecord saveWithBlock:^(NSManagedObjectContext *localContext) {
    ... = [MyEntity MR_inContext:localContext];
}];
```

**Comment by sryze** [comment]
I'm experiencing this problem with MagicalRecord 2.3.2. Objects are created in a child MOC created with  by a JSON mapper like this:

```objective-c
_managedObjectContext = [NSManagedObjectContext MR_context];

__weak typeof(self) weakSelf = self;
__block NSManagedObject *mappedObject;

return [self performBlockOnManagedContextQueue:^{
    mappedObject = ...; // create a new object inside self.managedObjectContext here
}].then(^{
    [weakSelf.managedObjectContext save];
}).then(^{
    return [mappedObject MR_inContext:[NSManagedObjectContext MR_defaultContext]];
});
```

The `performBlockOnManagedContextQueue` and `save` methods is simply a wrapper around `performBlock:` that returns a promise:

```objective-c
- (PMKPromise *)performBlockOnManagedContextQueue:(void(^)())block {
    NSAssert(block != nil, @"Block cannot be nil");
    return [PMKPromise promiseWithResolver:^(PMKResolver resolve) {
        [self.managedObjectContext performBlock:^{
            block();
            dispatch_async(dispatch_get_main_queue(), ^{
                resolve(nil);
            });
        }];
    }];
}

@implementation NSManagedObjectContext (PromiseKit)

- (PMKPromise *)save {
    return [PMKPromise promiseWithResolver:^(PMKResolver resolve) {
        [self MR_saveToPersistentStoreWithCompletion:^(BOOL contextDidSave, NSError *error) {
            if (error == nil) {
                resolve(@(contextDidSave));
            } else {
                resolve(error);
            }
        }];
    }];
}

@end
```

Even though I save the default context prior to calling `MR_inContext:` it still returns `nil` for some reason. Could it be that the save operation hasn't finished yet when `MR_saveToPersistentStoreWithCompletion` called the completion block?

I have also tried replacing the `MR_inContext` call with this as suggested in earlier posts:

```
[[NSManagedObjectContext MR_defaultContext] objectWithID:object.objectID];
```

But it resulted in objects with temporary object IDs and I was getting a crash at a later point:

```
2016-10-25 11:23:14.634 ONSITE[53074:4387092] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'cannot find data for a temporary oid: XXX 
```
