### ISSUE TITLE
No KVO notification received using block saving methods

### ISSUE THREAD

**Issue by robreuss** [magicalpanda/MagicalRecord#196]
I've registered to receive notifications for objects that are being saved using saveInBackgroundWithBlock and do not receive the notifications.  I've tried it as well with saveWithBlock and do not receive notifications with that method either.  

If I do the updates using the default context or contextForCurrentThread, along with MR_save, the notification are received perfectly, so I know that I am properly registered to receive them.

**Comment by KieranMcGrady** [comment]
I know this is an old issue but I'm facing the same problem. I was saving to the default context using ```saveToPersistentStoreWithCompletion``` and just transitioned to ```saveWithBlock```. 

I use the KVO notifications to update my UI with the new data. The data is definitely getting pushed to the default context as a manual refresh of my view shows the new data but the notifications are not getting fired.

I can workaround it by firing my own notification in the completion block to  trigger the UI update but I'm sure that wouldn't be 100% reliable.

**Comment by tonyarnold** [comment]
@KieranMcGrady can you show me the basics of your code? What property are you observing using KVO? I'll need a bit more info before I can help.

**Comment by KieranMcGrady** [comment]
@tonyarnold Sure, thanks. These are the observers:

```
    [[NSNotificationCenter defaultCenter] addObserver:self
                                             selector:@selector(objectChanged:)
                                                 name:NSManagedObjectContextObjectsDidChangeNotification
                                               object:[NSManagedObjectContext MR_defaultContext]];
    
    [[NSNotificationCenter defaultCenter] addObserver:self
                                             selector:@selector(objectSaved:)
                                                 name:NSManagedObjectContextDidSaveNotification
                                               object:[NSManagedObjectContext MR_defaultContext]];
```

I can't provide the full code for the saves but I've made it as close as possible substituting some pseudocode:

```

        [op start:^(NSError * error, NSData * data) {
            if (!error) {
                dispatch_async(dispatch_get_main_queue(), ^(){
                    [MagicalRecord saveWithBlock:^(NSManagedObjectContext *localContext) {
                        MyObject *myObject = (MyObject *)[localContext existingObjectWithID:oid error:nil];
                        [myObject setData:data];
                    } completion:^(BOOL success, NSError *error) {
                        [MagicalRecord saveWithBlock:^(NSManagedObjectContext *localContext) {
                            [op start:^(NSError *error, NSData *data) {
                                if (!error) {
                                    dispatch_async(dispatch_get_main_queue(), ^(){
                                        [MagicalRecord saveWithBlock:^(NSManagedObjectContext *localContext) {
                                            MyObject *myObject = (MyObject *)[localContext existingObjectWithID:oid error:nil];
                                            NSString *s = [[NSString alloc] initWithData:data encoding:NSUTF8StringEncoding];
                                            [myObject setMyString:s];
                                        } completion:^(BOOL success, NSError *error) {
                                            if (complete)complete();
                                        }];
                                    });
                                }
                            }];
                            
                        } completion:^(BOOL success, NSError *error) {
                        }];
                    }];
                });
            }
        }];
    }

```
The saves are both successful and if I manually reload my data the updates pulled from the default context are visible so I'm not sure when the notifications aren't getting fired.

**Comment by Alydyn** [comment]
What version of MagicalRecord are you using?  I believe there was a bug in one of the 2.3 beta version where context saving & notification was not set up correctly. See [this release](https://github.com/magicalpanda/MagicalRecord/releases/tag/v2.3.0-beta.5).

Also why do you call `dispatch_async` and then call `+saveWithBlock:completion:`?  `+saveWithBlock:completion:` calls the `completion` block on the main queue.

**Comment by KieranMcGrady** [comment]
@Alydyn I ran ```[MagicalRecord version]``` and it returned 230. I call dispatch_async because the operation is on the background thread. I know it seem like a strange mix of dispatch calls but that was the only way I could get the save to succeed.

Is 230 the version with the bug?

**Comment by Alydyn** [comment]
The bug was in v2.3beta4, and was fixed in the release that I linked, v2.3beta5.

Those calls to `dispatch_async` are completely superfluous.  Do you have [Core Data concurrency debugging](http://oleb.net/blog/2014/06/core-data-concurrency-debugging/) turned on?  If those operations are on a background thread, what you are effectively doing is starting on a background thread, calling to the main queue, then using MagicalRecord to create a background save block, which then calls the completion block on the main queue, where you promptly send another block to MagicalRecord on a background queue and then you dispatch to the main queue and create a background save block again!  Most likely the problem could have been resolved by using an `NSManagedObjectContext` created in your operation with `NSPrivateQueueConcurrencyType` and calling `-performBlock:` or `-performBlockAndWait:` on that context and making sure concurrency debugging is on.

**Comment by KieranMcGrady** [comment]
@Alydyn Thanks for the tips re concurrency. I'll look into how I'm doing that and work on improving it. I'm not sure for the exact MR version as it was integrated into the project before I took it over - the only number I can find is the 230 from the version method. I'm willing to guess I'm not on the latest version though so I'll work on upgrading it and return here with the results.

**Comment by KieranMcGrady** [comment]
I have removed my manual installation of MR and replaced it with the version available on Cocoapods so I am now definitely up-to-date (2.3.0). I also remove the extraneous dispatch_async call and enabled concurrency debugging (great tip btw). Unfortunately the notification is still not getting called. According to the logs the save is definitely taking place.

```
Saving <NSManagedObjectContext (0x16119440): saveWithBlock:completion:> on a background thread
 → Saving <NSManagedObjectContext (0x14d61350): MagicalRecord Root Saving Context> on a background thread
```

Fortunately I have a workaround for this using a completion block and updating my view when the completion block is called however I would really like to get this working to cut down on duplicate code as I do other UI updates via the Core Data notifications.
