### ISSUE TITLE
Parse issue (expected a type) in NSNumber+MagicalDataImport.h

### ISSUE THREAD

**Issue by ynechaev** [magicalpanda/MagicalRecord#212]
Expected a type errors in NSNumber+MagicalDataImport.h:

``` objective-c
#import <Foundation/Foundation.h>

@interface NSNumber (MagicalRecord_DataImport)

- (NSString *) MR_lookupKeyForAttribute:(NSAttributeDescription *)attributeInfo; //Expected a type error
- (id) MR_relatedValueForRelationship:(NSRelationshipDescription *)relationshipInfo; //Expected a type error

@end
```

Apple LLVM Compiler 3.1
iOS 5.1 target
XCode Version 4.3.2 (4E2002)

**Comment by mamuncseruet03** [comment]
I have solved this issue by adding .pch file with following content
//
// Prefix header for all source files of the 'MagcalRecord Example' target in the 'MagcalRecord Example' project
//

#import <Availability.h>

#ifndef __IPHONE_3_0
#warning "This project uses features only available in iOS SDK 3.0 and later."
#endif

#ifdef __OBJC__
    #import <UIKit/UIKit.h>
    #import <Foundation/Foundation.h>
#endif

//1. Import MagicalRecord Sources
#define MR_SHORTHAND
#define MR_ENABLE_ACTIVE_RECORD_LOGGING 0
#import "CoreData+MagicalRecord.h"
