### ISSUE TITLE
Odd behavior while managing multiple data stores

### ISSUE THREAD

**Issue by Marxon13** [magicalpanda/MagicalRecord#270]
I'm trying to convert multiple databases (made of plist files), into multiple core data databases, and am experiencing some odd behavior. (especially after the commit on Oct 2nd). 

I'm converting the databases with a loop preforming in a background thread and in the main thread;
-  I start in the background thread, creating a stack with <code>setupCoreDataStackWithStoreNamed:</code>. 
- Then I add all of my entities and save in the background thread.
-  Calling back to the main thread I preform <code>[MagicalRecord cleanUp]; </code>and release the background thread.
- If I need to convert another database, I recreate the background thread, and preform these actions again.

First, <code>[MagicalRecord cleanUp] </code> is not tearing down and deallocating the entire data stack. The same NSPersistentStoreCoordinator is reused each loop, and one the same three NSManagedObjectContexts that are created are reused each time. If I use NSLogs to check the values of these objects in MagicalRecord.h, they are set to nil after cleanUp, but during the start of the next loop they are recovered, and used again. Causing each separate database being saved to be saved to the first store that is created, and ignoring the last created store.

Second, <code> [NSManagedObjectContext MR_resetContextForCurrentThread];</code> or any similar reset method is not "forgetting" all of its NSManagedObjects. And when the context gets reused, all of the data from the previous database still exists.

Third, before the October 2nd update, directly after calling <code>[managedObjectContext MR_saveNestedContexts];</code> I was able to preform <code>[NSManagedObjectContext MR_resetContextForCurrentThread];</code> immediately afterward without error. After October 2nd, If I reformed this method, on the next loop I would get an assertion failure <code>**\* Assertion failure in +[NSManagedObjectContext MR_defaultContext]</code>

Before this update it was my understanding that when MagicalRecord saves on a background thread, it copies the NSManagedObjectContext being saved. So I can edit the context after saving, and nothing would happen to the saving context. Has this changed?

I tried to make this issue as non-application specific as I could. If you want to see what I'm doing specifically, I have a stackOverflow question with my code: http://stackoverflow.com/questions/12700590/switching-between-core-data-stores

**Comment by wongzigii** [comment]
@gianlo86 Thanks for you code.
