### ISSUE TITLE
How to set the fetchLimit ?

### ISSUE THREAD

**Issue by flypigz** [magicalpanda/MagicalRecord#283]
currently the MagicalRecord does not accept the fetchLimit as a parameter, but It does provide many + (id) MR_findFirst_XXX methods. 

may be we should add one method like this:
- (NSArray *) MR_findAllSortedBy:(NSString *)sortTerm ascending:(BOOL)ascending withPredicate:(NSPredicate *)searchTerm withFetchLimit:(NSInteger)limit;

it also can replace some of the MR_findFirst_XXX methods by set the fetchLimit as 1.

**Comment by VAlexander** [comment]
@casademora Awesome solution. Appreciate for all the hard work. :+1:
