### ISSUE TITLE
Potential bug when importing ordered one-to-many relationship

### ISSUE THREAD

**Issue by ychw** [magicalpanda/MagicalRecord#300]
Currently, this part is handled in category NSManagedObject+MagicalDataImport, method:

<pre>- (void) MR_addObject:(NSManagedObject *)relatedObject forRelationship:(NSRelationshipDescription *)relationshipInfo
</pre>

In this method, the selector name is defined as:

<pre>
        if ([relationshipInfo respondsToSelector:@selector(isOrdered)] && [relationshipInfo isOrdered])
        {
            //Need to get the ordered set
            NSString *selectorName = [[relationshipInfo name] stringByAppendingString:@"Set"];
            relationshipSource = [self performSelector:NSSelectorFromString(selectorName)];
            addRelationMessageFormat = @"addObject:";
        }
</pre>

As you can see, if my entity has a relationship "members", the selector generated from this method will be "membersSet", which is not part of the NSManagedObject subclass file auto-generated from Xcode.

**Comment by LeeCQ** [comment]
@magicalpanda/team-magicalrecord

**Comment by YevhenMekhedov** [comment]
I have faced with that issue today and I have no idea how to avoid it except of not using ordered to-many relationship. Version 2.4.0
