### ISSUE TITLE
Data for NSDate type of attribute was preprocessed before hitting the custom "import<AttrName>" method

### ISSUE THREAD

**Issue by ychw** [magicalpanda/MagicalRecord#303]
This happens in NSAttributeDescription+MagicalDataImport.m, line 35. I think since user already provided custom method to process the data, it should be used first to deal with the raw data, instead of the processed the data based this framework's assumption. In my case, the timestamp field is a unix timestamp; and in my Core Data entity, the field is NSDate. Above logic prevents me from importing the timestamp field properly. 

I think the proper way is to move the logic to NSManagedObject+JSONHelpers.m, method

<pre>- (void) MR_setAttributes:(NSDictionary *)attributes forKeysWithObject:(id)objectData
</pre>

Something like this:

<pre>
        if (lookupKeyPath) 
        {
            id value = [attributeInfo MR_valueForKeyPath:lookupKeyPath fromObjectData:objectData];
            if (![self MR_importValue:value forKey:attributeName])
            {
                if ([attributeInfo attributeType] == NSDateAttributeType)
                {
                    if (![value isKindOfClass:[NSDate class]])
                    {
                        NSString *dateFormat = [[attributeInfo userInfo] valueForKey:kMagicalRecordImportCustomDateFormatKey];
                        value = dateFromString([value description], dateFormat ?: kMagicalRecordImportDefaultDateFormatString);
                    }
                    //            value = adjustDateForDST(value);
                }

                [self setValue:value forKey:attributeName];
            }
        } 
        else { ... }
</pre>

**Comment by AnthonyMDev** [comment]
I just had this same issue, and I solved it by implementing my own date setter in an override of `didImport`. This way it overwrites whatever other date MagicalRecord sets.

Wanted to offer the solution in case anyone else ever comes across this.
