### ISSUE TITLE
How to do lightweight migration with MR?

### ISSUE THREAD

**Issue by ychw** [magicalpanda/MagicalRecord#323]
I use this statement to start my data store:

<pre>
    [MagicalRecord setupCoreDataStackWithAutoMigratingSqliteStoreNamed:@"Kotor.sqlite"];
</pre>

However, after adding an extra field to an entity, the app crashes with error:

Can't merge models with two different entities named ...

What should I do in this case? Is there a general guide to implement lightweight migration in MR? For example, attribute / relationship type changes, attribute name changes, remove / add attributes.

Thanks

**Comment by marianoabdala** [comment]
For the record, I do have two different models that contain an entity with the same name (so, not a versioning issue) and setting:
`[MagicalRecord setDefaultModelNamed:@"MyModel.momd"];`

Right before:
`[MagicalRecord setupCoreDataStackWithAutoMigratingSqliteStoreNamed:[@"MyDb.sqlite"]];`

Fixed it for me.

**Comment by yasirmturk** [comment]
Solution is 
'MagicalRecord.setDefaultModelNamed("CleverBinder.mom")
        MagicalRecord.setupAutoMigratingCoreDataStack()'

**Comment by SerhiiMatvieiev** [comment]
@yasirmturk Good solution! But this clear all data. Is there a way to save the data?

**Comment by rockylive** [comment]
For me worked solution was 
```
MagicalRecord.setupCoreDataStack(withAutoMigratingSqliteStoreNamed: "MyDB.sqlite") 
MagicalRecord.setDefaultModelNamed("MyModel.momd")
MagicalRecord.setupAutoMigratingCoreDataStack()
```
