### ISSUE TITLE
fetchAllWithDelegate: causes application crash

### ISSUE THREAD

**Issue by huix9527** [magicalpanda/MagicalRecord#348]
MRCategory is a simple core data entity in my case, which contains only one field: categoryName, I added the following line in my code:

[MRCategory fetchAllWithDelegate:self]

The application crashes, judging by the output: 
'An instance of NSFetchedResultsController requires a fetch request with sort descriptors'
It seems that a sort descriptor needs to be set to the request before constructing the NSFetchedResultsController.

**Comment by pronebird** [comment]
This method seems valid to me and useful. Instead I have to manually deal with FRC. What is the problem to add this method? I might be wrong but it seems to me as a good way to monitor a light-weight table for changes.

```objc
    NSFetchRequest *fetchRequest = [OptionModel MR_createFetchRequest];
    fetchRequest.sortDescriptors = @[];
    self.optionsFetchedResultsController = [OptionModel MR_fetchController:fetchRequest delegate:self useFileCache:NO groupedBy:nil inContext:[NSManagedObjectContext MR_defaultContext]];
    [self.optionsFetchedResultsController performFetch:nil];
```

**Comment by Rehanmeo** [comment]
NSInvalidArgumentException', reason: 'An instance of NSFetchedResultsController requires a fetch request with sort descriptors'


I am Facing this problem in my application to connect CoreData in Swift 3.0.1 so friend any to help me for this problem
