### ISSUE TITLE
Calling saveToPersistentStoreWithCompletion blocks main thread when saving to disk

### ISSUE THREAD

**Issue by bachand** [magicalpanda/MagicalRecord#377]
My understanding was that the goal of having the root NSManagedObjectContext was to allow (potentially time-consuming) saves to disk to happen on a background thread.  However, when calling saveToPersistentStoreWithCompletion on the default NSManagedObjectContext (or a nested NSManagedObjectContext), the main thread blocks while waiting for the root NSManagedObjectContext to save to the persistent store.

For example, when running some code like this:

```
dispatch_queue_t queue = DISPATCH_QUEUE_PRIORITY_BACKGROUND, 0);
dispatch_async(dispatch_get_global_queue(queue, ^{
    [[NSManagedObjectContext defaultContext] saveToPersistentStoreWithCompletion:^(BOOL success, NSError *error) {
        NSLog(@"saved");
    }];
});
```

The log reads:

```
-[NSManagedObjectContext(MagicalSaves) MR_saveWithOptions:completion:](0x9962e40) → Saving <NSManagedObjectContext (0x9962e40): *** DEFAULT ***> on *** BACKGROUND THREAD ***
-[NSManagedObjectContext(MagicalSaves) MR_saveWithOptions:completion:](0x9962e40) → Save Parents? 1
-[NSManagedObjectContext(MagicalSaves) MR_saveWithOptions:completion:](0x9962e40) → Save Synchronously? 0
-[NSManagedObjectContext(MagicalRecord) MR_contextWillSave:](0x9962e40) Context DEFAULT is about to save. Obtaining permanent IDs for new 141 inserted objects
-[NSManagedObjectContext(MagicalSaves) MR_saveWithOptions:completion:](0x9d61bc0) → Saving <NSManagedObjectContext (0x9d61bc0): *** BACKGROUND SAVING (ROOT) ***> on *** MAIN THREAD ***
-[NSManagedObjectContext(MagicalSaves) MR_saveWithOptions:completion:](0x9d61bc0) → Save Parents? 0
-[NSManagedObjectContext(MagicalSaves) MR_saveWithOptions:completion:](0x9d61bc0) → Save Synchronously? 1
-[NSManagedObjectContext(MagicalRecord) MR_contextWillSave:](0x9d61bc0) Context BACKGROUND SAVING (ROOT) is about to save. Obtaining permanent IDs for new 141 inserted objects
-[NSManagedObjectContext(MagicalSaves) MR_saveWithOptions:completion:]_block_invoke_021(0x9d61bc0) → Finished saving: <NSManagedObjectContext (0x9d61bc0): *** BACKGROUND SAVING (ROOT) ***> on *** MAIN THREAD ***
```

As you can see, the root NSManagedObjectContext is saving synchronously on the main thread.  This behavior doesn't seem expected to me, but I could be missing something too...

**Comment by timothyrobb** [comment]
Has there been any news on this at all?

I'm still seeing this issue:
```
2015-07-20 14:51:30.576 DummyAppName[77147:3874990] → Saving <NSManagedObjectContext (0x7d66b300): Networking Context> on a background thread
2015-07-20 14:51:30.577 DummyAppName[77147:3874854] → Saving <NSManagedObjectContext (0x78ee3fb0): MagicalRecord Default Context> on the main thread
2015-07-20 14:51:30.577 DummyAppName[77147:3874854] → Saving <NSManagedObjectContext (0x798c6c20): MagicalRecord Root Saving Context> on the main thread
```
The "Networking Context" is a child of the default, as is standard pattern. I would expect the Root Saving Context to run on a background thread.

**Comment by timothyrobb** [comment]
@tonyarnold
Never mind, disregard my message.
After reading a bunch of open and closed issues I finally stumbled across my issue, that MR does not support my stack architecture of having working contexts child contexts of the default context.
No worries, I'll put the workers on the root context (as is default) and see how I can manage the data this way.

Cheers.

**Comment by tonyarnold** [comment]
Sorry @timothyrobb — this one fell through the cracks. Feel free to ask on StackOverflow, or here if you need some help.
