### ISSUE TITLE
Documentation says we can set the defaultContext but it is actually a private method

### ISSUE THREAD

**Issue by chourobin** [magicalpanda/MagicalRecord#390]
The documentation references the following:

And, if you want to make myNewContext the default for all fetch requests on the main thread:
[NSManagedObjectContext MR_setDefaultContext:myNewContext];

However, I am unable to set the default context since this method is private. Is this function not available in the master yet?

**Comment by blwinters** [comment]
I'm not very proficient with Objective-C. Does anyone know how to achieve the same thing with a Swift `extension`?
