### ISSUE TITLE
Make Magical Record more flexible by not requiring a default context.

### ISSUE THREAD

**Issue by brutella** [magicalpanda/MagicalRecord#405]
Don't get me wrong, Magical Record is already pretty flexible when it comes to setting up Core Data. My main problem is that some methods like `MR_save[...]` requires a default context because of the if statement in `NSManagedObjectContext+MagicalSave.m:83`

```
if (self == [[self class] MR_defaultContext]) {...}
```

In my case I use multiple persistent store coordinators and therefore multiple managed object contexts. When I save the context with `MR_save[...]` I get an assertion failure because no default context is set. I have to remove the assertion to not crash the app.

Issue #395 is about the same problem.

**Comment by Buju77** [comment]
Is this fixed with MR 2.3.0 release?
