### ISSUE TITLE
EXC_BAD_ACCESS when app is updated from App Store

### ISSUE THREAD

**Issue by roland9** [magicalpanda/MagicalRecord#454]
when an app is updated from the app store, it crashes at first launch (after the update) with the crash log below. This happens at the first attempt to save to the persistent store.
deleting and re-installing the app fixes the issue - potentially related to Core Data migration issues?

Remark: the core data stack is setup via setupCoreDataStackWithAutoMigratingSqliteStoreNamed:

thanks for any hints!

Exception Type:  EXC_BAD_ACCESS (SIGSEGV)
Exception Codes: KERN_INVALID_ADDRESS at 0x00000008
Crashed Thread:  0

Thread 0 name:  Dispatch queue: com.apple.main-thread
Thread 0 Crashed:
0   libsystem_kernel.dylib          0x3935f838 __kill + 8
1   APPNAME-TEST                    0x001797dc CLSSignalHandler + 188
2   libsystem_c.dylib               0x392e0d38 _sigtramp + 40
3   Foundation                      0x319e5b2c -[NSError dealloc] + 56
4   libobjc.A.dylib                 0x38e69490 (anonymous namespace)::AutoreleasePoolPage::pop(void*) + 164
5   CoreFoundation                  0x310b482c _CFAutoreleasePoolPop + 12
6   Foundation                      0x319e6d86 -[NSAutoreleasePool drain] + 118
7   CoreData                        0x30f6a6ac -[NSManagedObjectContext save:] + 1204
8   APPNAME-TEST                    0x000f38f4 __70-[NSManagedObjectContext(MagicalSaves) MR_saveWithOptions:completion:]_block_invoke3 + 136
9   CoreData                        0x30f6ddb6 developerSubmittedBlockToNSManagedObjectContextPerform + 86
10  CoreData                        0x30f6dee6 -[NSManagedObjectContext performBlockAndWait:] + 90
11  APPNAME-TEST                    0x000f3828 -[NSManagedObjectContext(MagicalSaves) MR_saveWithOptions:completion:] + 248
12  APPNAME-TEST                    0x00051c22 -[BBModel storeInfo:](BBModel.m:3841)
13  APPNAME-TEST                    0x0004720a __29-[BBModel loadInfoWithBlock:]_block_invoke (BBModel.m:1608)
14  APPNAME-TEST                    0x00094cb4 __74+[AFJSONRequestOperation JSONRequestOperationWithRequest:success:failure:]_block_invoke + 96
15  libdispatch.dylib               0x39286790 _dispatch_call_block_and_release + 8
16  libdispatch.dylib               0x392865d8 _dispatch_client_callout + 20
17  libdispatch.dylib               0x39289e40 _dispatch_main_queue_callback_4CF + 224
18  CoreFoundation                  0x311451ac __CFRunLoopRun + 1284
19  CoreFoundation                  0x310b8238 CFRunLoopRunSpecific + 352
20  CoreFoundation                  0x310b80c4 CFRunLoopRunInMode + 100
21  GraphicsServices                0x34c97336 GSEventRunModal + 70
22  UIKit                           0x32fd42b4 UIApplicationMain + 1116
23  APPNAME-TEST                    0x0003cf0e main (main.m:16)
24  APPNAME-TEST                    0x0003cec4 start + 36

**Comment by Svantulden** [comment]
I have this problem too with my update to the app store. My (relevant) stacktrace: 

```
Thread : Crashed: com.apple.main-thread
0  libobjc.A.dylib                0x38538626 objc_msgSend + 5
1  Foundation                     0x2e6a0d9d -[NSError dealloc] + 60
2  libobjc.A.dylib                0x3853db6b objc_object::sidetable_release(bool) + 174
3  libobjc.A.dylib                0x3853e0d7 (anonymous namespace)::AutoreleasePoolPage::pop(void*) + 358
4  CoreFoundation                 0x2dcb1c19 _CFAutoreleasePoolPop + 16
5  Foundation                     0x2e6ab637 -[NSAutoreleasePool drain] + 122
6  CoreData                       0x2daf2fb9 -[NSManagedObjectContext save:] + 944
7  {APPNAME}                      0x0015a715 __70-[NSManagedObjectContext(MagicalSaves) MR_saveWithOptions:completion:]_block_invoke20 + 1705749
8  CoreData                       0x2db56935 developerSubmittedBlockToNSManagedObjectContextPerform + 88
```

Funnily enough, Crashlytics decides to not group these crashes together. So I have around 30 single crashlogs that all have the same stacktrace. Some context: 

```
All happen on iPhone 4 or iPad 2
All on iOS 7.1.2
I have an iPhone 4 as test device with iOS 7.1.2 but I cannot reproduce the issue (I also updated from app store while previous version was active with data in it), so I guess it doesn't happen on all devices
I am using MagicalRecord (release) version 2.3.0
```

I hope this helps. If you need more information, don't hesitate to ask. Could it have something to do with the iOS version or the architecture of the iPhone 4/iPad 2? (Don't they both have the same architecture?)

**Comment by elsurudo** [comment]
I'm experiencing this issue as well. Not sure it's due to migration yet, but basically a few users send me their SQLite files after an upgrade, and they appear to be corrupted.
