### ISSUE TITLE
"Can't find model for source store" during lightweight migration

### ISSUE THREAD

**Issue by kevboh** [magicalpanda/MagicalRecord#466]
I'm having an issue when trying to do a lightweight migration. I'm using an auto-migrating sqlite store. My change was the addition of three properties, two to one entity and one to another:

Entity 1:
Added Boolean property, non-optional, default NO
Added Boolean property, non-optional, default NO, indexed

Entity 2:
Added Integer16 property, non-optional, default 0, min 0, max 2

These changes were made in a new version of my model and the current version of the .xcdatamodeld version was set to this version.

I have Core Data debugging flags turned on. Upon installing the app with these changes on top of my App Store version I get an error when trying to add a persistent store:

```
CoreData: error: (migration) migration failed with error Error Domain=NSCocoaErrorDomain Code=134130 "The operation couldn’t be completed. (Cocoa error 134130.)" UserInfo=0x13eb8550 {URL=file://localhost/Users/kevboh/Library/Application%20Support/iPhone%20Simulator/6.1/Applications/BF71D6DC-96C1-4B47-AA37-45AD04EE8C19/Library/Application%20Support/MyApp/MyApp.sqlite, metadata={
    NSPersistenceFrameworkVersion = 419;
    NSStoreModelVersionHashes =     {
        Entity1 = <18df2417 18ccbdfa 5e2a58c1 7da2666f 1265354a 748364ea 6e3616b2 11ce3261>;
        Entity2 = <65daf369 bd62ca2c 0ae00fbf b34e2bc3 3e3cba49 7ac58e23 81e902b8 4008f537>;
        Entity3 = <56900773 4a5dda47 2ef8a37e 8db90c97 10d10a9c 29803a01 7dab6e94 4adf075d>;
    };
    NSStoreModelVersionHashesVersion = 3;
    NSStoreModelVersionIdentifiers =     (
        ""
    );
    NSStoreType = SQLite;
    NSStoreUUID = "530C03F6-B17A-4ABA-946B-4C66F04D3107";
    "_NSAutoVacuumLevel" = 2;
}, reason=Can't find model for source store}
```

I checked the hashes of my old model in the VersionInfo.plist file located in my app bundle. The hashes for the two entities in my old model version match those listed in the error... so I'm not sure why it can't find the old version.

Any ideas?

**Comment by naveenkumar-sourcebits** [comment]
@kevboh : Is there some issue in apple code for migration, bcos even I have same problem and my app is unable to find the source model file. Any solutions?

**Comment by kevboh** [comment]
@naveenkumar-sourcebits I never found away around this beyond manual migration or wiping the database. At WWDC 2013 I was told there was an edge case in CoreData where some models failed lightweight migration, but I wasn't told what changes triggered the failure and if there's a workaround. In the end I wrote a manual migration step.

**Comment by naveenkumar-sourcebits** [comment]
@kevboh: Thanks, I will check how to do manul migration

**Comment by naveenkumar-sourcebits** [comment]
@kevboh : Manual migration solved the issue, thanks for your time and support.
