### ISSUE TITLE
Importing Data

### ISSUE THREAD

**Issue by emadd** [magicalpanda/MagicalRecord#532]
I'm getting a strange error (EXC_BAD_ACCESS by CFStringGetLength within NSManagedObject(MagicalRecord)MR_executeFetchRequest:inContext:) I can't make sense of when attempting to import data from a JSON file...

```
NSManagedObjectContext *opContext = [NSManagedObjectContext MR_contextForCurrentThread];

    NSString *jsonPath = [[NSBundle mainBundle] pathForResource:@"DefaultData"
                                                         ofType:@"json"];
    NSData *data = [NSData dataWithContentsOfFile:jsonPath];

    NSError *parseError;
    NSDictionary *json = [NSJSONSerialization JSONObjectWithData:data options:kNilOptions error:&parseError];

    NSArray *dataTypes = [json objectForKey:@"dataTypes"];

    [MagicalRecord saveWithBlockAndWait:^(NSManagedObjectContext *localContext) {
        for (NSDictionary *obj in dataTypes) {
            DLog(@"%@", obj);
            [BTDataType MR_importFromObject:obj inContext:localContext];
        }
    }];

    NSError *saveError;
    [opContext save:&saveError];
```

The entity is very simple, just two properties: importKey (int16) and name (String)...

The JSON is like...

{
    "dataTypes":[
         {
             "importKey":1000,
             "name":"DataType A"
         },
         {
             "importKey":1001,
             "name":"DataType B"
         },
         {
             "importKey":1002,
             "name":"DataType C"
         },
         {
             "importKey":1003,
             "name":"DataType D"
         }
    ]
}

**Comment by ITyXNikhilB** [comment]
Hi!!! I have added relatedBy attribute to my entity still I am getting same crash. Can you help me with this?

**Comment by ITyXNikhilB** [comment]
Following is my stackTrace
----------------------------------------
SIGSEGV: Application terminated
1
libobjc.A.dylib in 0x197784000
2
CoreData in 0x181f30000
3
CoreData in 0x181f30000
4
CoreData in 0x181f30000
5
CoreData in 0x181f30000
6
CoreData in 0x181f30000
7
CoreData in 0x181f30000
8
CoreData in 0x181f30000
9
CoreData in 0x181f30000
10
CoreData in 0x181f30000
11
CoreData in 0x181f30000
12
CoreData in 0x181f30000
13
CoreData in 0x181f30000
14
appName in __67+[NSManagedObject(MagicalRecord) MR_executeFetchRequest:inContext:]_block_invoke (NSManagedObject
15
CoreData in 0x181f30000
16
CoreData in 0x181f30000
17
appName in +[NSManagedObject(MagicalRecord) MR_executeFetchRequest:inContext:] (NSManagedObject
18
appName in +[NSManagedObject(MagicalFinders) MR_findByAttribute:withValue:inContext:] (NSManagedObject
19
appName in +[NSManagedObject(MagicalFinders) MR_findByAttribute:withValue:] (NSManagedObject
20
appName "MyEntity.m" line 40 in +[MyEntity settingNamed:]
21
