### ISSUE TITLE
Update podspec to let user choose if logs are ON or OFF

### ISSUE THREAD

**Issue by AliSoftware** [magicalpanda/MagicalRecord#545]
Each time I do a `pod update` on my project, [Cocoapods](http://cocoapods.org/) retrieve the `MagicalRecord` pod without its `#define MR_ENABLE_ACTIVE_RECORD_LOGGING 0` set in its `Pods-{TargetName}-MagicalRecord-prefix.pch` files so I have to edit all those `.pch` files to disable the logs after each `pod update`.

Would it be possible to use supspecs so that the user can select if he wants to retreive MagicalRecord with logs ON or OFF by default?

---

Something maybe like this in the `MagicalRecord.podspec` should do the trick (not tested):

``` ruby
s.prefix_header_contents = <<-EOS
#ifdef __OBJC__
#define MR_SHORTHAND
#import "MagicalRecordConfig.h" // Import the config depending on the subspec
#import "CoreData+MagicalRecord.h"
#endif
EOS

s.default_subspec 'logsOn'
s.subspec 'logsOn' do |sp|
  s.source_files 'Configs/LogsOn/MagicalRecordConfig.h' // Use this MagicalRecordConfig.h file to turn logs ON
end
s.subspec 'logsOff' do |sp|
  s.source_files 'Configs/LogsOff/MagicalRecordConfig.h' // Use this MagicalRecordConfig.h file to turn logs OFF
end
```

And of course adding to the source repo a `Config/LogsOn/MagicalRecordConfig.h` file with `#define MR_ENABLE_ACTIVE_RECORD_LOGGING 1` in it and a `Config/LogsOff/MagicalRecordConfig.h` file with `#define MR_ENABLE_ACTIVE_RECORD_LOGGING 0` in it.

---

This way, users can either specify `pod 'MagicalRecord/logsOn'` or `pod 'MagicalRecord/logsOff'` in their `Podfile`. (`pod 'MagicalRecord'` will defaults to same as `pod 'MagicalRecord/logsOn'`).

**Comment by sokol8** [comment]
Hi guys,

I'm a bit confused. The latest version of Magical record available through the pods is 2.2 (dated June 2013) which doesn't contain

[MagicalRecord setLogLevel:MagicalRecordLogLevelVerbose]; 

How can I get access to MagicalRecord setLogLevel: functionality?

**Comment by Alydyn** [comment]
You'll want to have CocoaPods get the develop branch:
https://github.com/magicalpanda/MagicalRecord/issues/932#issuecomment-68157192

**Comment by AliSoftware** [comment]
@sokol8 this feature is only a available in MagicalRecord 3.0 which, AFAIK, is still in RC. While 3.0 — which is a major rewrite — continues to be tested and developed until it's official release, 2.2 remains the latest *stable* version.

You may either wait for 3.0 to be officially out of RC (the official MR maintainers like @tonyarnold might tell you if they plan to release it soon or if they have other priorities) or you can test it right away without waiting — simply use the dedicated branch/tag of the GIT repo, by specifying it in your Podfile to enforr using it.

**Comment by Alydyn** [comment]
@AliSoftware I just checked the headers for MR v2.3beta5 and it includes the method he references:
https://github.com/magicalpanda/MagicalRecord/blob/v2.3.0-beta.5/MagicalRecord/Core/MagicalRecord%2BOptions.h#L146

I believe he can get that version with CocoaPods by following the link in my previous comment.

**Comment by Alydyn** [comment]
@AliSoftware also I disagree about 2.2 being the latest stable version.  v2.3 is really what you want to be on (the develop branch)

**Comment by AliSoftware** [comment]
> @AliSoftware I just checked the headers for MR v2.3beta5 and it includes the method he references:

Good catch. I thought it was only introduced in 3.0 and was on my iPhone when answered so didn't take the time to check the source code. Thanks!

> @AliSoftware also I disagree about 2.2 being the latest stable version. v2.3 is really what you want to be on (the develop branch)

Same as above, didn't check as I was posting from my iPhone, thanks for correcting me. I edited my comment to change it to `2.x` which was what I actually meant.

Bottom line is: this method is not included in the last official released pod, but is available in other branches and anyone can point to those branches if they don't want to wait for the official release of these methods.
