### ISSUE TITLE
Support creating a temporary object (MOC = nil) with +createInContext:

### ISSUE THREAD

**Issue by airdrummingfool** [magicalpanda/MagicalRecord#546]
Using `+createInContext:` and passing `nil` results in an assertion error. Creating the entity using the standard `initWithEntity:insertIntoManagedObjectContext:` and passing `nil` for the context works, and returns an instance of the entity that is not persisted on any context. This is useful for creating temporary objects that do not get saved or show up in fetches.

`+createInContext` calls `+insertInManagedObjectContext:` (which is on the entity generated with Mogenerator), which performs an assert on the MOC and then calls `[NSEntityDescription insertNewObjectForEntityForName:inManagedObjectContext:]`.

**Comment by marcmatta** [comment]
Hi @tonyarnold,

Problem still persists and only works as described by lukedixon. It would be a lot cleaner to write

```
ManagedObject *managedObject = [ManagedObject MR_createEntityInContext:nil];
manageObject.title = @"Title";

// Now save:
[MagicalRecord saveWithBlock:^(NSManagedObjectContext *localContext) {
    [localContext insertObject:managedObject];
}]
```

Any plans to fix this bug in the near future?

Thanks!
