### ISSUE TITLE
MR_contextForCurrentThread used of ThreadContext is problematic

### ISSUE THREAD

**Issue by carlshimer** [magicalpanda/MagicalRecord#566]
General problem:

Our application supports the ability for the user to log out and log in again with a different user name / password.  We were seeing strange issues and /or crashes with core Data after a user logged out and logged in again.

Here is what we are doing under the hood:
1) When user clicks logout, we shutdown all our operation queues, clean up Magical record using the cleanup method, and finally delete the sqlite database.
2) User logs in, we set up core data / magical record from scratch.
3) Download data from the server.

What I noticed is that was that on some occasions it looked like we were getting data from the old database despite the fact that it had been deleted and Magical record had been cleaned up / shutdown.  I finally tracked down the problem to MR_contextForCurrentThread returning a NSManagedObjectContext from the ThreadContext that was created with the old database.  Said another way, despite shutting down my operation queues as cleanly as possible the system is still reusing threads and the thread local storage associated with them.  

I figured out that what I really need was to iterate through all of my threads and call MR_resetContextForCurrentThread.  I honestly don't know of an easy way to do that - you can iterate threads at the C level using mach based APIs but not sure you can get access to the ThreadContext.  Another possibility is to broadcast a message to all threads using notifications but this seems problematic as well since you don't have control over which thread runs the notification handler.

The fundamental problem seems to be that OperationQueue's use threads but want to hide the details from you while CoreData absolutely requires you to be aware of thread management.

My current solution is to use a global runcount unsigned integer that I increment when the user logs out.  I modified MR_contextForCurrentThread to check for this global variable (via the AppDelegate) and reset the thread local MOC.  So far this has fixed my problems.

Has anyone run into this problem or can offer an alternative solution? I can make this into a pull request if anyone is interested...

**Comment by grittymindy** [comment]
I've read this issue description and all the comments, also the [post](http://saulmora.com/coredata/magicalrecord/2013/09/15/why-contextforcurrentthread-doesn-t-work-in-magicalrecord.html) by @casademora. Still don't know why a reused thread and the cached MOC in thread context will cause the crash. The MOC is not used by a different thread, but the same one, right?  Can you explain that in detail, please? @carlshimer @casademora @daveanderson Thanks a lot!

**Comment by tonyarnold** [comment]
So the most basic answer is this: threads do not equate to GCD queues, so stashing against the current thread is no guarantee that the queue will end up using the same thread in future. Also, as of iOS 9/OS X 10.11, confinement contexts are deprecated.

Core Data uses queues to manage much of it's thread confinement in more recent versions, so stashing a private (or main) queue NSManagedObjectContext into a thread's dictionary is no guarantee that that thread is the one that the context will use (in fact, I can guarantee you that it won't be). 

You should be using `-[NSManagedObjectContext performBlock:…]` and `-[NSManagedObjectContext performBlockAndWait:…]` in your apps now, and forget about managing threads yourself where Core Data is involved entirely.

Apple provides more detail on how to work with Core Data and concurrency in their [Core Data Programming Guide](https://developer.apple.com/library/tvos/documentation/Cocoa/Conceptual/CoreData/Concurrency.html#//apple_ref/doc/uid/TP40001075-CH24-SW1). It's also probably worthwhile gaining a deeper understanding of dispatch queues too: [Concurrency Programming Guide — Dispatch Queues](https://developer.apple.com/library/ios/documentation/General/Conceptual/ConcurrencyProgrammingGuide/OperationQueues/OperationQueues.html)

**Comment by grittymindy** [comment]
@tonyarnold Thanks for the detailed explanation.  That is very clear.
