### ISSUE TITLE
Support progressive data migrations

### ISSUE THREAD

**Issue by tonyarnold** [magicalpanda/MagicalRecord#636]
As per [the description in objc.io issue 4’s article on Core Data Migrations](http://www.objc.io/issue-4/core-data-migration.html#progressive_migrations), MagicalRecord should support progressive migration.

**Comment by Ricardo1980** [comment]
Hello!
It seems this progressive migration feature was added a couple of years ago to version 3.0, but right now we only have v2.3.3.
I think this is a really useful feature. More or less when is it going to be available?
Thanks!
