### ISSUE TITLE
Xcode warnings with Cocoapods (MR_SHORTHAND)

### ISSUE THREAD

**Issue by Bruno-Furtado** [magicalpanda/MagicalRecord#652]
**Xcode displays warning messages**

Probably these are presented because I'm using Cocoapods. 
As Cocoapods uses a separate `.xcodeproj`, he is not able to find the `#define MR_SHORTHAND` add in Prefix file of my project.

**Warnings**

NSManagedObject+MagicalDataImport.m
- `Undeclared selector shouldImport:`
- `Undeclared selector willImport:`
- `Undeclared selector MR_valueForUndefinedKey:`
- `Undeclared selector didImport:`

NSManagedObject+MagicalRecord.m
- `Undeclared selector entityInManagedObjectContext:`
- `Undeclared selector insertInManagedObjectContext:`

**Environment**
- Xcode 5.1 (5B90f)
- Deployment Target: 6.0
- Base SDK: 7.1
- Valid Architectures: arm64, armv7, armv7s

**Comment by jlnbuiles** [comment]
hi, 

is there an ETA for 2.3?

**Comment by werediver** [comment]
@jlnbuiles It seems that there is only one issue left till 2.3.0: https://github.com/magicalpanda/MagicalRecord/milestones/2.3.0
But I'm not sure whether any other issues may be added to the list.

**Comment by tonyarnold** [comment]
Hopefully there are no more issues for 2.3.0. I haven't made time to reproduce the remaining bug, but once that's resolved I'd be happy to release.

**Comment by pavm035** [comment]
Hi,

Even i'm facing the same issue, and i would like to understand what is the current MagicalRecord version to use in pod?. By default it comes with 2.2 but i see several branches here with tag release/3.0 and so, would you please help me to get out of these issues?

Thanks in advance

**Comment by danipralea** [comment]
Hello. 
Having the same issue here
