### ISSUE TITLE
Importing an empty array causes a crash

### ISSUE THREAD

**Issue by BarryBatser** [magicalpanda/MagicalRecord#654]
When trying to import a empty array, it causes a crash because it is trying to fetch it later on.

**Comment by Coeur** [comment]
I tried `NSArray *entity = [[self testEntityClass] MR_importFromArray:@[] inContext:[NSManagedObjectContext MR_defaultContext]];` on master branch, and no crash.

For reference, line 173 at the time of the post was:
https://github.com/magicalpanda/MagicalRecord/blob/44bc0da1db8ed5a633e2785c4b242761aaabb449/MagicalRecord/Categories/NSManagedObject/NSManagedObject%2BMagicalDataImport.m#L172-L174
But this part of the code is nowadays in a try-catch.

So I'll close this issue for now. If there is a misunderstanding, you'd need to show a piece of code (similar to what I tried in my first paragraph) to demonstrate the issue and get it re-opened.
