### ISSUE TITLE
saveWithBlock:completion: -- success = NO, but error = nil on object with validation issues

### ISSUE THREAD

**Issue by mmccroskey** [magicalpanda/MagicalRecord#683]
I'm working in a test-driven fashion on a project that uses MagicalRecord, and uses XCTest for testing. I have an NSManagedObject subclass, let's call it `Thing`, which has a **required** property `name`:

``` objc
@interface Thing : NSManagedObject
@property (nonatomic, retain) NSString * name;
@end

@implementation Thing
@dynamic name;
@end
```

When I create a test that creates a new `Thing`, sets its `name`, and saves using `saveWithBlock:completion:`, everything works fine:

``` objc
Thing *thing = [Thing MR_createEntity];
thing.name = @"thing";

__block BOOL saveSuccess = NO;
__block NSError *saveError = nil;
__block BOOL saveFinished = NO;
[MagicalRecord saveWithBlock:nil completion:^(BOOL success, NSError *error)
{
    saveSuccess = success;
    saveError = error;
    saveFinished = YES;
}];

WAIT_WHILE(!saveFinished, 10.0);
XCTAssertEqual(saveSuccess, YES, @"should succeed");
XCTAssertNil(saveError, @"should save");
XCTAssertEqual(saveError.code, (NSInteger)0, "not expecting validation errors");
```

All three of the `XCTest` assertions above pass.

**However**, if I create a test that creates a new `Thing`, **doesn't** set its `name`, and then saves using `saveWithBlock:completion:`...

``` objc
Thing *thing = [Thing MR_createEntity];

__block BOOL saveSuccess = NO;
__block NSError *saveError = nil;
__block BOOL saveFinished = NO;
[MagicalRecord saveWithBlock:nil completion:^(BOOL success, NSError *error)
{
    saveSuccess = success;
    saveError = error;
    saveFinished = YES;
}];

WAIT_WHILE(!saveFinished, 10.0);
XCTAssertEqual(saveSuccess, NO, @"should not succeed");
XCTAssertNotNil(saveError, @"should not save");
XCTAssertEqual(saveError.code, (NSInteger)1550, "expecting validation errors");
```

...I get unexpected results: the `XCTAssertEqual` assertion passes (i.e. `saveSuccess` = NO as expected), but the `XCTAssertNotNil` and `XCTAssertEqual` assertions fail (which I've confirmed to be because `saveError` is nil).

Thoughts?

**Comment by alexszilagyi** [comment]
While trying to save the I'm getting no error & no success. Any idea?

```
MagicalRecord.saveWithBlock({ (localContext : NSManagedObjectContext!) in

    let newUserInfo = UserInfo.MR_createEntityInContext(localContext)
    newUserInfo!.email = self.emailTextField.text!
    newUserInfo!.password = self.passwordTextField.text!
    newUserInfo!.client_id = self.userNameTextField.text!
    newUserInfo!.user_id = userInfoResponse?.userId

          }, completion: { (success : Bool, error : NSError?) in
            print(success) // it returns always false or 0
})
```

**Comment by mmccroskey** [comment]
Hi @alexszilagyi -- it's been years (as you can see!) since I've worked with MagicalRecord, so I'm afraid I can't help. Perhaps @tonyarnold could lend a hand?

**Comment by tonyarnold** [comment]
Hey @mmccroskey and @alexszilagyi I'm basically out at this stage, too. 

From what I recall, the save methods returns a `nil` error and `NO` as the status if there is nothing to save. It's not the intuitive response in my opinion, but it is what Core Data is documented as doing (MagicalRecord is just passing along the result of the call to `save:`). 

Your best bet is to turn the logging level up and have a read through the logs that MR prints. If you can do this, feel free to paste the logs back here (or in a gist) and @ mention me again.

**Comment by alexszilagyi** [comment]
@mmccroskey : Yeah, just asked :smiley: 

@tonyarnold : Thanks, I've managed to solve it by using the following approach:

```
let localContext = NSManagedObjectContext.MR_defaultContext()
Person.MR_truncateAllInContext(localContext)
let person = Person.MR_createEntityInContext(localContext)
person!.gender = 0
person!.firstName = "First name"
person!.lastName = "Last name"
          
localContext.MR_saveToPersistentStoreWithCompletion({ (success : Bool, error : NSError?) -> Void in
    // and here I get success true ;)
 })
```
