### ISSUE TITLE
Reset in memory store

### ISSUE THREAD

**Issue by codeboost** [magicalpanda/MagicalRecord#714]
I'm using an in-memory store to run some unit tests on CoreData objects.
I need a way to completely re-create the in-memory store with no data in it between tests, as my unit tests expect the store to be empty.
This doesn't seem to work (store still has data in it!):

```
[NSPersistentStore MR_setDefaultPersistentStore:nil];
[NSManagedObjectModel MR_setDefaultManagedObjectModel:nil];
[NSPersistentStoreCoordinator MR_setDefaultStoreCoordinator: nil];
[NSPersistentStore MR_setDefaultPersistentStore:nil];
[MagicalRecord setupCoreDataStackWithInMemoryStore];
```

How should I do it then ?

**Comment by nonstriater** [comment]
@tonyarnold when the version3 will be release?

**Comment by nonstriater** [comment]
@codeboost I found the + MR_setDefaultContext: is a private method in v2.2,u should not use like that?
I replace it with + (void) MR_resetDefaultContext but failed

**Comment by nonstriater** [comment]
@all I found the method +(void) cleanUp in the MagicalRecord.h. so the + (void)resetInMemoryStore thould be like:

+ (void)resetInMemoryStore{
[MagicalRecord cleanUp];
    //And set up the store again
    [MagicalRecord setupCoreDataStackWithInMemoryStore];
}
