### ISSUE TITLE
Can’t update relationship with null value.

### ISSUE THREAD

**Issue by pedroviana** [magicalpanda/MagicalRecord#727]
After create a record with a valid relationship, the importFromObject can’t save the relationship when the value is null from the json.

In other words, I cant update a relationship to null.

**Comment by burczyk** [comment]
I can confirm - I'm facing it right now. Here was a proposed PR for that https://github.com/magicalpanda/MagicalRecord/pull/1053 but it was closed.
However suggested version is not fully correct, second code section doesn't take `mappedKeyName` under consideration. Fixed second block:

```objective-c
if ([relatedObjectData isEqual:[NSNull null]])
{
	[self setValue:nil forKey:relationshipName];
	continue;
}
```

And everything works like a charm. Will create a PR later.
