### ISSUE TITLE
iCloud issue with contentNameKey on iOS7

### ISSUE THREAD

**Issue by amilloy** [magicalpanda/MagicalRecord#787]
I am getting an error in the console log when trying to get iCloud working with MR Core Data:

[PFUbiquitySetupAssistant validateOptionsWithError:](334): CoreData: Ubiquity:  Invalid option: the value for NSPersistentStoreUbiquitousContentNameKey should not contain periods: <my bundle ID>

(See https://devforums.apple.com/message/865393 for a similar instance of the problem)
Problem seems to go away if I use a contentNameKey without dots (e.g. substitute ~ for periods) - so maybe that's the answer.

**Comment by tonyarnold** [comment]
I've just updated the code to match what Apple expects by default — a nil value. If you want to set your own, that's fine, but the defaults shouldn't blow up in your face anymore: e3f4159aba1d3e6082fae41573691e232042a9fa
