### ISSUE TITLE
Mantle compatibility

### ISSUE THREAD

**Issue by onmyway133** [magicalpanda/MagicalRecord#814]
I'm using Mantle to convert JSON <-> MTLModel <-> NSManagedObject. As it points out, we all work with MTLModel

http://www.andyshep.org/2013/07/17/using-mantle-with-core-data.html

```
MFMarketModel *market = [MTLJSONAdapter modelOfClass:[MFMarketModel class]
                                      fromJSONDictionary:obj
                                                   error:NULL];
```

But the way MagicalRecord works is to provide categories to NSManagedObject subclass
http://ablfx.com/blog/article/2
which means a lot of useful methods, like MR_findAll, MR_findFirst, ... only works if we are subclassing NSManagedObject

So how do we use Mantle, but still benefit from MagicalRecord ?

**Comment by skywinder** [comment]
What about mantle 2.0?
 https://github.com/Mantle/Mantle/blob/2.0/CHANGELOG.md

It seems, that with new implementation with protocol there is a way to use it together!
