### ISSUE TITLE
iOS8 bug : concurrency debug fails on NSManagedObjectContext::workingName

### ISSUE THREAD

**Issue by jeremiegirault** [magicalpanda/MagicalRecord#828]
Using the new flag provided for debugging in iOS8, the app stops when CoreData concurrency rules are violated :

```
-com.apple.CoreData.ConcurrencyDebug 1
```

It seems that workingName in NSManagedObjectContext::workingName in NSManagedObjectContext+MagicalRecord fails because of the access to [self userInfo]. Sad but true.

My rough fix allows things to work :

``` objc
- (void) MR_setWorkingName:(NSString *)workingName;
{
    [self performBlockAndWait:^{
        [[self userInfo] setObject:workingName forKey:kMagicalRecordNSManagedObjectContextWorkingName];
    }];
}

- (NSString *) MR_workingName;
{
    __block NSString *workingName = nil;
    [self performBlockAndWait:^{
        workingName = [[self userInfo] objectForKey:kMagicalRecordNSManagedObjectContextWorkingName];
    }];

    if (nil == workingName)
    {
        workingName = @"UNNAMED";
    }
    return workingName;
}
```

Maybe you will find something better.

Thanks

**Comment by ryanjm** [comment]
@tonyarnold - [Right above](https://github.com/magicalpanda/MagicalRecord/blob/8d22b3b682caf09b521aedba160f48353a9d684d/MagicalRecord/Categories/NSManagedObjectContext/NSManagedObjectContext%2BMagicalSaves.m#L54) your change is a place that references `MR_workingName` for the log, what is the recommended way of handing that?

```objc
MRLogVerbose(@"NO CHANGES IN ** %@ ** CONTEXT - NOT SAVING", [self MR_workingName]);
```
