### ISSUE TITLE
[MagicalRecord setLoggingMask:] no known method for selector 'setLoggingMask'

### ISSUE THREAD

**Issue by callzhang** [magicalpanda/MagicalRecord#836]
I tried to set the logging level as given in tutorial, but I got this:
[MagicalRecord setLoggingMask:] no known method for selector 'setLoggingMask'

I pulled the latest version:
pod 'MagicalRecord', :git => 'https://github.com/magicalpanda/MagicalRecord' , :tag =>'v2.3.0-beta.3'
Any explanation?

**Comment by amitoj** [comment]
Hi, 
I'm using MagicalRecord version 2.2.0 and I can't find the 'setLoggingLevel' method 

#import "CoreData+MagicalRecord.h"
...
[MagicalRecord setLoggingLevel:MagicalRecordLoggingLevelVerbose];
