### ISSUE TITLE
MR_aggregateOperation:@"max:" not returning highest value above 9

### ISSUE THREAD

**Issue by Spokane-Dude** [magicalpanda/MagicalRecord#859]
This is my code:
    -(NSString *) findHighestSKU  {

```
int highestSKU  = [[Books MR_aggregateOperation:@"max:" onAttribute:@"sku" withPredicate:nil]intValue];

return [NSString stringWithFormat:@"%d", highestSKU];
}
```

The values in the SKU attribute are 1-10; when this executes, it returns 9; I increase it, add the record with a SKU of 10 (verified).  Run the app again, it should return 10, but it returns 9 each time.  I should mention that SKU is stored as NSString in CoreData.

**Comment by souvickcse** [comment]
Is there any other way to typecast the column without the above mentioned solutions?

**Comment by Coeur** [comment]
@souvickcse 
fetch the array of values first, then find the max value through `[NSString compare:options:NSNumericSearch]`.
