### ISSUE TITLE
PLEASE, HELP!! "MR_entityName" doesn't return correct name on Swift

### ISSUE THREAD

**Issue by mhergon** [magicalpanda/MagicalRecord#864]
Hi,

When I try to check if entity exists, the app crashes;

```objective-c
if var app = App.MR_findFirst() {

}
```

After some investigation, the problem is on "MR_entityName" method. This returns incorrect name for entity:

![screen shot 2014-09-30 at 19 39 53](https://cloud.githubusercontent.com/assets/621373/4463339/2a072a9c-48ca-11e4-8cdd-5169bea4d17b.png)

With this error, console outputs this message;

```
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'NSFetchRequest could not locate an NSEntityDescription for entity name 'Onlyn.App'
```

Any help? Please, solve as soon as posible. 
Thanks!

--------- EDIT 1
A possible temporary solution could be:

```objective-c
if ([entityName length] == 0)
    {
        entityName = [NSStringFromClass(self) stringByReplacingOccurrencesOfString:@"Onlyn." withString:@""];
    }
```

--------- EDIT 2
Others possible solution:
https://developer.apple.com/library/prerelease/mac/documentation/Swift/Conceptual/BuildingCocoaApps/WritingSwiftClassesWithObjective-CBehavior.html

```swift
let myPersonClass: AnyClass = NSClassFromString("MyGreatApp.Person")
```

**Comment by thedamfr** [comment]
Class computed variable could use : 
```
let classString = NSStringFromClass(classType.self)
let range = classString.rangeOfString(".", options: NSStringCompareOptions.CaseInsensitiveSearch, range: Range<String.Index>(start:classString.startIndex, end: classString.endIndex), locale: nil)
return classString.substringFromIndex(range!.endIndex)

```

**Comment by thedamfr** [comment]
Actually this extension is a valid bugfix :
```
extension NSManagedObject {
    
    class func MR_entityName() -> NSString {
        let classString = NSStringFromClass(self)
        let range = classString.rangeOfString(".", options: NSStringCompareOptions.CaseInsensitiveSearch, range: Range<String.Index>(start:classString.startIndex, end: classString.endIndex), locale: nil)
        return classString.substringFromIndex(range!.endIndex)
    }
    
}
```

**Comment by csotiriou** [comment]
This will not work in Swift 1.2, and it produces an error, regarding "Method redeclares Objective-C method"

It's a change in Swift 1.2

**Comment by flandy84** [comment]
maybe the MR_entityName should be generic enough to work with both swift and obj-c nsmanagenedobject-subclasses (and survive/avoid swift 1.2 swift-extension/objc-c category redeclaration collisions)

just an idea from the swift-world:

        NSStringFromClass(self).componentsSeparatedByString(".").last!
