### ISSUE TITLE
MR v2.3.beta3 - on iOS 8, saving background context at same time as MR_fetch on default_context causes deadlock

### ISSUE THREAD

**Issue by hretarekar** [magicalpanda/MagicalRecord#865]
Saving a private queue child context of root_context, at the same time as a MR_fetch is issued on default_context causes a deadlock. Check https://github.com/hretarekar/MR_iOS8_Freeze_BackgroundContext for sample code which freezes.

Deadlock threads stack shown in below images
![screen shot 2014-10-01 at 3 50 15 pm](https://cloud.githubusercontent.com/assets/2031869/4473567/b2218014-4954-11e4-9fc6-c026cbbc5b7a.png)

![screen shot 2014-10-01 at 3 50 33 pm](https://cloud.githubusercontent.com/assets/2031869/4473574/ba250a2e-4954-11e4-9a2a-30f5b6ceaa0a.png)

The same code implemented without Magical Record, using core data setup shown in sample code at http://code.tutsplus.com/tutorials/core-data-from-scratch-core-data-stack--cms-20926 doesn't seem to cause the deadlock

I confirmed this issue is not happening on iOS 7, it only started happening on iOS 8.

**Comment by sammy-SC** [comment]
@hretarekar hello, i know it has been a while but i would like to ask whether you managed to solve the issue in a clean way? Thanks

**Comment by golopupinsky** [comment]
I'm also experiencing this on iOS 8 only. Crashes on saving if FRC was previously filtered with predicate.  Aforementioned workaround (locking root context) does not help me at all. 
But I've found another one - setting frc.delegate to nil before saving.

**Comment by iskhakovs** [comment]
@hretarekar hello! I have exactly same issue on iOS 9.3.2, but my app deadlocks only if i use not nil groupedBy parameter in _fetchController = [PZFeedItem MR_fetchController:self.fetchRequest delegate:self useFileCache:NO groupedBy:self.sectionNameKeyPath inContext:[NSManagedObjectContext MR_defaultContext]]. MagicalRecord v2.3.3. Have you found clean way to fix this issue? Thanks
