### ISSUE TITLE
Completion hander in saveWithBlock... not called during Unit Test

### ISSUE THREAD

**Issue by gearoidoceallaigh** [magicalpanda/MagicalRecord#867]
It seems as though the completion block handler doesn't fire in an XCTestCase test. Pretty simple to test like so:

``` objective-c
[MagicalRecord saveWithBlock:^(NSManagedObjectContext *localContext) {
     # persist some object 
} completion:^(BOOL success, NSError *error) {
     NSLog(@"MY WIIIIIIFE"); // never gets called
}];
```

The only reason I can think this would be the case is that the test case finished before the completion handler can be called.

**Comment by kunass2** [comment]
the same problem
