### ISSUE TITLE
Handle enum

### ISSUE THREAD

**Issue by cHaLkdusT** [magicalpanda/MagicalRecord#905]
Hi magicalpanda,

Hope there could be a helper method to easily insert enum values as NSNumber or any related int values to Core Data, instead of hacking up NSNumber and creating category.

Regards,
chlkdst

**Comment by tonyarnold** [comment]
@cHaLkdusT could you elaborate on what you're asking for here? Stashing enumeration values into Core Data is pretty much a case-by-case scenario — there's no guarantee about the numeric format of the contents of the enum, so I'm not sure we could write something effective or simple to do what I think you're suggesting.

**Comment by cHaLkdusT** [comment]
Hi @tonyarnold ,

Suppose I have an object Student that an object attribute of "gender". Programmatically I would prefer to create an enum Gender with MALE and FEMALE enumerations. It has two advantages, firstly this would lessen typo error compared to using "male" and "female" String objects. Secondly, is this much readable than using BOOL value or 1 and 0 value. 

Is there already a way of catching this problem with MagicalRecord, or is this a possible new feature to add on?

Regards,
chlkdst

**Comment by tonyarnold** [comment]
I don't think I explained that very well. Your enumeration looks something like this, right?

```objective-c
typedef NS_ENUM(NSInteger, MRGender)
{
    MRGenderFemale,
    MRGenderMale,
    MRGenderOther,
    MRGenderUnspecified
};
```

So those values are `NSIntegers`, and Core Data will store them as `NSIntegers`: there's no information stored alongside those values that indicates that they are a valid value of `MRGender` — they'll be `1` or `3` or `46`. You can safely convert the returned `NSNumber` from Core Data into an `NSInteger` using `-[NSNumber integerValue]` and then cast it to your enum, like so:

```objective-c
NSNumber *genderNumber = [myManagedObject valueForKey:@"gender"];
NSInteger genderValue = [genderNumber integerValue];
MRGender gender = (MRGender)genderValue;
```

_You could merge the last two lines into one, but for clarity's sake let's leave them separate._

You can define a custom property on your managed object subclasses that does the above work for you and exposes the value as the "proper" enumeration value, but that's specific to your subclass and your implementation.

Do you see what I'm getting at? I'm all ears if you have ideas about what else we can try here, but this is pretty standard Objective-C — I don't think there's much MagicalRecord could add here that would be generic enough to be used with all enums.

**Comment by cHaLkdusT** [comment]
Hi @tonyarnold ,

Very well said. Thanks for clarifying my inquiry. The main purpose of this thread is that if we could create a utility class for handling enums, however just like what you said, I should create helper method to convert my enums to NSNumber.

Closing this issue now.

Thanks,
cHaLkdusT
