### ISSUE TITLE
Background MOC changes not propagated to default MOC (faulted issue)

### ISSUE THREAD

**Issue by newmanw** [magicalpanda/MagicalRecord#929]
Please forgive as I am not sure this is a bug with MagicalRecord, could be a bug/limitation with CoreData, but I am not sure.

I have a UI that can create Reports and Documents (child of a report).  The way the server works I have to submit the Report first then I can submit the Documents for that Report.  I am trying to do that work (submitting to the server) on background threads.

In the UI on the default context I save the parent entity and the children:
```objective-c
NSManagedObjectContext *context = [NSManagedObjectContext MR_defaultContext];
Report *report = [Report MR_createInContext:context];
report.dirty = YES;
Document *document =  [Document MR_createInContext:context];
document.dirty = YES;
document.report = report;
[report setDocumentsObject:document];

// save it
[context MR_saveToPersistentStoreWithCompletion:^(BOOL success, NSError *error) {
    NSLog(@"saved the report");
}];
```

This works great, its saved to default context.

I have NSFetchedResultsControllers setup to listen to the 'dirty' attribute on the Report so I know when to save it to the server:
```objective-c
self.managedObjectContext = [NSManagedObjectContext MR_context];
[self.managedObjectContext MR_observeContext:[NSManagedObjectContext MR_defaultContext]];
        
self.fetchedResultsController = [Report MR_fetchAllSortedBy:@"timestamp"
                                                       ascending:NO
                                                  withPredicate:[NSPredicate predicateWithFormat:@"dirty == YES"]
                                                         groupBy:nil
                                                        delegate:self
                                                       inContext:self.managedObjectContext];
```

This also works great, since I observe the default context the fetched results controller sees the change and can send it to the server.

This is where my problem starts.  When I get back the server response for the Report i get back an id for that report.  I use that id in the url to submit the document.  I use the same background MOC as above when I set the remoteId on the Report entity:

```objective-c
NSOperation *pushOperation = [self operationToPushReport:report success:^(id response) {
    NSLog(@"Successfully submitted report");
    report.remoteId = [response objectForKey:@"id"]; // set id from server
    report.dirty = [NSNumber numberWithBool:NO];
            
    [self.managedObjectContext MR_saveToPersistentStoreWithCompletion:^(BOOL success, NSError *error) {
        NSLog(@"Success, saved to persistent store");
    }];
} failure:^{
    NSLog(@"Error submitting report");
 }];
```

I listen to submit the documents like this:
```objective-c
self.managedObjectContext = [NSManagedObjectContext MR_context];
[self.managedObjectContext MR_observeContext:[NSManagedObjectContext MR_defaultContext]];
        
self.fetchedResultsController = [Document MR_fetchAllSortedBy:@"lastModified"
                                                       ascending:NO
                                                  withPredicate:[NSPredicate predicateWithFormat:@"report.remoteId != nil && dirty == YES"]
                                                         groupBy:nil
                                                        delegate:self
                                                       inContext:self.managedObjectContext];
```

More simply I listen for all documents that are dirty and have a parent (Report) that has a remoteId.  However that fetchedResultsController does not recognize the change.  I think this might have something to do with the fact that the remoteId save was done on a background MOC and the default MOC is not seeing the change.

Notice that I call
```objective-c
[self.managedObjectContext MR_saveToPersistentStoreWithCompletion:^(BOOL success, NSError *error) {
```
That was a last ditch effort to save to PS to see if that helped. I was previously calling:
```objective-c
[self.managedObjectContext MR_saveOnlySelfWithCompletion:^(BOOL success, NSError *error) {
```

Regardless, same issue.

Possibly linked to these issues:
https://stackoverflow.com/questions/3923826/nsfetchedresultscontroller-with-predicate-ignores-changes-merged-from-different

http://stackoverflow.com/questions/14018068/nsfetchedresultscontroller-doesnt-call-controllerdidchangecontent-after-update

Am I possibly doing something wrong?  Is this possibly a bug in MR?

If this really is still a bug/limitation in CoreData does MR provide a facility to 'fix' this?  If not has that even been considered?

Seems to be somewhat common, and does not really make sense IMHO

**Comment by Alydyn** [comment]
@newmanw Can you watch for save notifications for the contexts you want to watch, and when you get one, re-execute the fetch on the `NSFetchedResultsController` so that it brings in the changed data?

Also, can you close this issue to clean up the issues area? 

Thanks!

**Comment by newmanw** [comment]
@Alydyn yeah there are a few different ways to work around FRC limitations, watch for MOC didSave notification, or override the didSave method in the entity that I care about.

Sorry I can definitely close this issue.

IMHO I would love to see MR provide a mechanism  to watch for saves within a MOC for a particular entity with a predicate.

I.E. if you watch ddiSave on MOC you get saves for all entities.  If you override didSave on an entity you get saves for only that entity but for all MOC's.

Do you think its worth writing an issue (feature) for that?

**Comment by Alydyn** [comment]
I think it is definitely an interesting feature, but I'm not sure it's aligned with the intent of MagicalRecord.  MagicalRecord seems to want to be more of a group of "helpers" to streamline using Core Data and reduce the amount of repetitive boilerplate code that a developer has to write.  What you are describing sounds like completely new functionality.

That being said, you could implement what you describe and create a pull request, and see what happens!
