### ISSUE TITLE
MagicalRecord (2.2.0) setLoggingLevel not available

### ISSUE THREAD

**Issue by amitoj** [magicalpanda/MagicalRecord#938]
Hi, 

I'm using MagicalRecord version 2.2.0 and I can't find the 'setLoggingLevel' method

```objective-c
#import "CoreData+MagicalRecord.h"
...
[MagicalRecord setLoggingLevel:MagicalRecordLoggingLevelVerbose];
```

Did I miss something?

Thanks.

**Comment by tonyarnold** [comment]
Control over logging isn't in a "release" version of MagicalRecord yet — if you need that feature, it's available on the `develop` branch in the upcoming Magical Record 2.3 release.
