### ISSUE TITLE
One save to a background MOC causing FRC didUpdate to fire twice

### ISSUE THREAD

**Issue by newmanw** [magicalpanda/MagicalRecord#940]
Not sure if this is normal behavior but I am seeing an insert and an update get fired when an entity is saved to a background MOC.

I watch the default MOC:

```objective-c
        self.fetchedResultsController = [MyEntity MR_fetchAllSortedBy:@"timestamp"
                                                               ascending:NO
                                                           withPredicate:[NSPredicate predicateWithFormat:@"field == 1"]
                                                                 groupBy:nil
                                                                delegate:nil
                                                               inContext:[NSManagedObjectContext MR_defaultContext]];
```

Creating and saving a new entity:
```objective-c
    self.managedObjectContext = [NSManagedObjectContext MR_context];
    self.myEntity = [MyEntity MR_createEntityInContext:self.managedObjectContext];

...

       [self.managedObjectContext MR_saveToPersistentStoreWithCompletion:^(BOOL success, NSError *error) {
        NSLog(@"saved the observation: %@", self.myEntity);
    }];
```

Is this expected behavior?

**Comment by Alydyn** [comment]
hello @newmanw,
I assume you mean the insert and update are fired in your `NSFetchedResultsController`?  If so, I think you must be doing some additional work else, as your newly created `self.myEntity` object would not appear in your FRC for the very reasons discussed in your previous issue.

Do you re-fetch the FRC somewhere?

**Comment by newmanw** [comment]
Look here for an example, hopefully its more clear ;)
https://github.com/newmanw/CoreDataFRC

Not really related to the other ticket.  FRC in UI watching default MOC.  Create entity in background context and save to PS.  When I do this the FRC gets an insert and update when saved.  Why not just an insert?

**Comment by Alydyn** [comment]
I ran your project and I only get an insert, not the update.
Also, I want to point out again that you are creating your objects wrong.  When you use Core Data with multiple threads you need to be *really* sure you are doing your work, even if that is accessing a property of an `NSManagedObject`, on the correct queue.

In the example you provided you create a new background context when the `UIButton` is tapped.  This is fine except that the background context then performs work right away, while it is still on the main thread from the button touch.
The correct way to do this is:
```obj-c
    NSManagedObjectContext *context = [NSManagedObjectContext MR_context];
    [context performBlockAndWait:^{ // you could use regular performBlock: here too
        
        Report *report = [Report MR_createEntityInContext:context]; //NOTE: I changed this method, the one you selected is deprecated
        report.dirty = [NSNumber numberWithBool:YES];
        report.timestamp = [NSDate date];
        
        NSLog(@"Saving.................................");
        [context MR_saveToPersistentStoreWithCompletion:^(BOOL success, NSError *error) {
            NSLog(@"Saved report to persistent store");
        }];

    }];
```

I think you should really enable Core Data Concurrency debug mode and you will see what I mean.
To do so, edit your scheme and under Run - Arguments, click the plus to add one:
`com.apple.CoreData.ConcurrencyDebug 1`

**Comment by newmanw** [comment]
@Alydyn no matter what I get the following:

![screen shot 2015-01-09 at 12 43 10 pm](https://cloud.githubusercontent.com/assets/3382274/5686311/0d9734fe-97ff-11e4-98fe-efccd3d4d27b.png)

Is not what you see?  If not I am not sure how my setup is different.  But I do see the create and update on my side.

Also, you are absolutely correct about the fact that I am using the wrong thread.  Screwed it up again as I am still learning :(

Maybe there is a better way, but did not see anything in docs when I looked which created the confusion.  
Basically I want to create a tmp MOC to throw away if the users cancels the new/edit operation.  As opposed to creating/modifying entities in default MOC (main thread) and then having to remove them or undo changes if they hit cancel.

What you describe with me current code means I have to do this:

```objective-c
// create and entity
[context performBlockAndWait:^{
        Report *report = [Report MR_createEntityInContext:context]; //NOTE: I changed this method, the one you selected is deprecated
}];
```

Then in another place when a mod happens:
```objective-c
// create and entity
[context performBlockAndWait:^{
report.someProperty = something;
}];
```

Then in another place when a read happens:
```objective-c
// create and entity
[context performBlockAndWait:^{
id foo = report.someProperty;
}];
```

Seems like a lot of work to have a tmp MOC that I can throw away (IE if users cancels creation or edit).  Is there a way to create a MOC on the current thread I am using (main in this case) so I don't have that extra work, but can still throw it away when done?

**Comment by Alydyn** [comment]
*  No, that is not what I see.  I only get the green label. What version of MR are you using?
*  Try creating a new main queue context and settings it's parent to the default:
```obj-c
NSManagedObjectContext *tempContext = [NSManagedObjectContext MR_newMainQueueContext];
tempContext.parentContext = [NSManagedObjectContext MR_defaultContext];
```
You can create/fetch/etc on this queue safely on the main thread.  Then you can either save or discard as needed.  
Honestly, though, I have taken to wrapping many of my object access calls in `-performBlock:` just to be certain.  I have found that it is easy to accidentally access an `NSManagedObject

**Comment by Alydyn** [comment]
Just answered my own question, you are using version 2.2.  You definitely want to be using 2.5beta5.  Go to the "Releases" link and download that version.  Alternatively you can edit your podfile since you are using CocoaPods, to pull version 2.3beta5.  I don't use CocoaPods so I'll have to hunt around for the way to do that.

**Comment by Alydyn** [comment]
Here is the comment that describes how to grab the latest:
https://github.com/magicalpanda/MagicalRecord/issues/868#issuecomment-57657088

**Comment by newmanw** [comment]
@Alydyn yup you can pull from git tags (which is awesome), thanks!

2.2 did in fact call create and update in the FRC, 2.3-beta.5 did not have that problem.  Not sure where this was fixed, but it was so closing the issue.

Also thanks so much for going above and beyond in explaining the ways of MR and CoreData.  I.E. looking at my code and pointing out problems unrelated to this issue, I truly appreciate it.  If you are ever in the Denver area I owe you a beer (or three)!

**Comment by Alydyn** [comment]
@newmanw glad to help, and beers sounds good! 
Too cold here now thought, -16 with windchill! (Dubuque IA area)
