### ISSUE TITLE
crash: "exc_bad_access kern_invalid_address" objc_msgsend _queueForDealloc

### ISSUE THREAD

**Issue by haemi** [magicalpanda/MagicalRecord#941]
In my app, I'm using MagicalRecord to deal with Core Data. Unfortunately, Crashlytics shows me several crashes where I have no clue why and where these happen:

![bildschirmfoto 2015-01-12 um 07 37 24](https://cloud.githubusercontent.com/assets/183958/5699688/e4e1734a-9a2d-11e4-8e9d-57232fab9a8a.png)

Does someone have an idea or faced similar problems?

**Comment by tonyarnold** [comment]
The backtrace for your crash doesn't include MagicalRecord at all. It's all Core Data. 

You can debug this issue using NSZombies — it looks like you've tried to access a managed object that you've already released.
