### ISSUE TITLE
Addng MagicalRecord 3 via CocoaPods error

### ISSUE THREAD

**Issue by Isuru-Nanayakkara** [magicalpanda/MagicalRecord#943]
I'm trying to add MagicalRecord 3 to a Swift project via CocoaPods (I use CocoaPods v0.36 beta which oficially supports both Obj-C and Swift pods).

I have added the following line to my Podfile, ran `pod install` and the library was added to the project successfully.

```
source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

platform :ios, '8.0'

pod 'MagicalRecord', :git => 'https://github.com/magicalpanda/MagicalRecord.git', :branch => 'release/3.0'
```

When I built the project, I didn't receive any compiler errors. Then I added this line `import MagicalRecord` to import the library to a file and built it again. I got the following error.

**Could not build Objective-C module 'MagicalRecord'**

Before this, I have added and used MagicalRecord 2.2 through CocoaPods and this error didn't occur then.

Any idea why this occur with version 3 and how to resolve this?

I uploaded to a Xcode project demonstrating this issue to my Dropbox [here](https://www.dropbox.com/s/o72e7fqiydo0d9p/MagicalRecord3test.zip?dl=0) if you want to take a quick look at it.

Thanks.

**Comment by tonyarnold** [comment]
Righto — I've added some missing header imports, but you also need to ensure that your project is set to have a deployment target of iOS 8.0 or higher. Proper Frameworks don't work prior to iOS 8.
