### ISSUE TITLE
crash with -com.apple.CoreData.ConcurrencyDebug 1 when fetching entites

### ISSUE THREAD

**Issue by JanC** [magicalpanda/MagicalRecord#950]
Hi,
every time I fetch and access a `NSManagedObject` in a background thread with `-com.apple.CoreData.ConcurrencyDebug 1`, I get a crash. It is reproducible with:

```objc
dispatch_async(dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_DEFAULT, 0), ^{
    PSPlayer *player = [[PSPlayer MR_findAll] firstObject];
    NSLog(@"player = %@", player.name);
});
```

I'm using `2.3.0 beta 5`

**Comment by Alydyn** [comment]
Thats because you are fetching in background without specifying a context.  `-MR_findAll` uses `MR_contextForCurrentThread` which is no longer recommended.
Try this:
```objC
NSManagedObjectContext *context = [NSManagedObjectContext MR_context];
[context performBlock:^{
    PSPlayer *player = [[PSPlayer MR_findAllInContext:context] firstObject];
    NSLog(@"player = %@", player.name);
}];
```

**Comment by JanC** [comment]
ok, I see. I thought that all the methods described in [the docs](https://github.com/magicalpanda/MagicalRecord/blob/develop/Docs/Fetching-Entities.md) were guaranteeing to use the appropriate context. Also, I have to surround the access with `[context performBlock:^{ ... ` so the docs are not yet updated for 2.3, correct?

**Comment by JanC** [comment]
Now, how come I have the crash when calling this in a `main` method of a `NSOperation` ?

```objc
- (void)main
{
    @autoreleasepool {
        NSManagedObjectContext *context = [NSManagedObjectContext MR_context];
        PSPlayer *player = (PSPlayer *) [context objectWithID:self.playerId];
        NSLog(@"name = %@", player.name);
        // rest  of NSOperation logic
    }
}
```

Do I have to wrap the entire logic of the NSOperation in `performBlockAndWait`
```objc
- (void)main
{
    @autoreleasepool {

        __block BOOL keepUpdating = YES;

        __block PSPlayer *player;
        NSManagedObjectContext *context = [NSManagedObjectContext MR_context];
        [context performBlockAndWait:^{
            player = (PSPlayer *) [context objectWithID:self.playerId];
            NSLog(@"name = %@", player.name);
            // rest  of NSOperation logic
        }];
    }
}
```

**Comment by Alydyn** [comment]
`NSOperation`'s `-main` method will almost certainly be called on a different thread than `-start` for concurrent operations.  First, try creating the context in `-start`.  And then, yes, you will need to wrap access in `-performBlockAndWait:`
An excellent write up is on [objc.io](http://www.objc.io/issue-2/common-background-practices.html)

**Comment by JanC** [comment]
ok thanks. objc.io is my Bible but it looks like I should read it more often. cheers
