### ISSUE TITLE
MR_importFromArray not working in 2.2 cocoa pods

### ISSUE THREAD

**Issue by airbob** [magicalpanda/MagicalRecord#954]
When will be version 3.0 available on cocoa pods?
```MR_importFromArray``` is still using asynchronous way to import, which is not correct
```objective-c
+ (NSArray *) MR_importFromArray:(NSArray *)listOfObjectData inContext:(NSManagedObjectContext *)context
{
    NSMutableArray *objectIDs = [NSMutableArray array];
    
    [MagicalRecord saveWithBlock:^(NSManagedObjectContext *localContext)
    {    
        [listOfObjectData enumerateObjectsWithOptions:0 usingBlock:^(id obj, NSUInteger idx, BOOL *stop) 
        {
            NSDictionary *objectData = (NSDictionary *)obj;
            NSManagedObject *dataObject = [self MR_importFromObject:objectData inContext:localContext];
            if ([context obtainPermanentIDsForObjects:[NSArray arrayWithObject:dataObject] error:nil])
            {
              [objectIDs addObject:[dataObject objectID]];
            }
        }];
    }];
    return [self MR_findAllWithPredicate:[NSPredicate predicateWithFormat:@"self IN %@", objectIDs] inContext:context];
}
```

Now I need to manually change it to saveWithBlockAndWait

**Comment by Alydyn** [comment]
Try using 2.3 from the develop branch.

**Comment by tonyarnold** [comment]
@airbob we don't really have a release date — it's really just as @casademora or I have time to work on the library that it progresses. 2.3 is pretty much ready to go, but 3.0 is a little ways off yet.

**Comment by tonyarnold** [comment]
@airbob — did the changes in the `develop` branch help at all?

**Comment by tonyarnold** [comment]
This doesn't appear to be relevant anymore, as I switched to using `performBlockAndWait:` on the passed context a while back — if the issue persists, please feel free to reopen this issue.
