### ISSUE TITLE
MR_findAllWithPredicate: not respecting order?

### ISSUE THREAD

**Issue by VAlexander** [magicalpanda/MagicalRecord#967]
Using my own conditions I create an array (let's call this ```stringsArray```) of strings, where order is crucial. There is no explicit order other than the one in which I added them in. With that said I use these strings to create an array of ```AwesomeObject```s whose ```awesomeString``` attribute matches a string in my `stringsArray`. 

Here's my predicate:
``` objective-c
NSPredicate *predicate = [NSPredicate predicateWithFormat:@"awesomeString in %@", stringsArray];
```

I then use my predicate to find the respective objects:
``` objective-c
NSArray *awesomeObjectsArray = [AwesomeObject MR_findAllWithPredicate:predicate];
```

The problem is that they don't always return in the order seen in ```stringsArray```. For example, if `stringsArray` had the following order:
``` objective-c
@[@"apple", @"kiwi", @"banana"];
```
My `awesomeObjectsArray` may return the following order:
``` objective-c
@[BananaObject, AppleObject, KiwiObject];
```

Am I missing a condition, or is this the expected behavior? If so what could I do to guarantee a matching order.

**Comment by Spokane-Dude** [comment]
Try something like this:  [<object> MR_findAllSortedBy: @"awesomeString"  ascending: YES];

**Comment by tonyarnold** [comment]
@Spokane-Dude is right — predicates imply no order. You need to sort the results after you get them, or use the method mentioned:

```objective-c
NSArray *awesomeObjectsArray = [AwesomeObject MR_findAllSortedBy:@"awesomeString" ascending:YES withPredicate:predicate inContext:localContext];
```

**Comment by VAlexander** [comment]
Sorry for the late reply. Thanks @Spokane-Dude  and @tonyarnold . Definitely helped, although I just ended up performing two separate calls instead, seeing that @Spokane-Dude's suggestion still wasn't working for me. I definitely understand why now. Appreciate the help! :+1:

**Comment by tonyarnold** [comment]
Good to hear :+1:
