### ISSUE TITLE
Swift Crashes when creating a new entity

### ISSUE THREAD

**Issue by csotiriou** [magicalpanda/MagicalRecord#972]
Hello,

I have been experiencing this crash when creating a new entity

2015-02-28 14:47:02.111 ParserTests[372:31150] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'executeFetchRequest:error: A fetch request must have an entity.'

This is because the entity name is being taken from the NSStringFromClass function, but in Swift, it will return something like "ModuleName.MyEntity" which is not the actual name of the entity stored.

Is there any way of bypassing this issue with swift?

**Comment by tonyarnold** [comment]
Hi @csotiriou — can you try with what's in the HEAD of the `develop` branch and see if it helps?

**Comment by csotiriou** [comment]
Same thing happens. 

+ (NSString *) MR_entityName;
{
    NSString *entityName;

    if ([self respondsToSelector:@selector(entityName)])
    {
        entityName = [self performSelector:@selector(entityName)];
    }

    if ([entityName length] == 0) {
        entityName = NSStringFromClass(self);
    }

    return entityName;
}


The NSStringFromClass returns (in my occasion) 'Parsertests.Article', not 'Article' as it would be the correct case.

**Comment by tonyarnold** [comment]
For now, please see the workaround here: https://github.com/magicalpanda/MagicalRecord/issues/864#issuecomment-70093892

**Comment by csotiriou** [comment]
The proposed solution will not work in Swift 1.2. I made a small pull request which solves all problems (hopefully)
