### ISSUE TITLE
Logging does not work

### ISSUE THREAD

**Issue by pronebird** [magicalpanda/MagicalRecord#979]
Hey,

I use MR via cocoa pods, any suggested methods to enable logging do not work.

Appdelegate:

```objc
#define MR_LOGGING_ENABLED 1
#import <MagicalRecord/CoreData+MagicalRecord.h>

@implementation AppDelegate

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions {
    [MagicalRecord setLoggingLevel:MagicalRecordLoggingLevelVerbose];
    return YES;
}

@end
```

I removed unnecessary code from example above, I definitely fetch and insert records using MR.

I suspect if I set MR_LOGGING_ENABLED for pod then this will work but this is PITA. Can we leverage environment variables to avoid this C black magic with defines and precompiler flags? CoreData uses env too.

**Comment by FloresRobles** [comment]
+1

**Comment by codigodelsur** [comment]
+1

**Comment by tonyarnold** [comment]
I'm still working on this for version 2.3. 

Right now, `MR_LOGGING_ENABLED` lets you choose not to enable logging. Frameworks ignore this build setting, so I'm thinking about enabling logging permanently, and then you can use the `setLoggingLevel:` method to turn it off if you need to.

Happy for input on this.

**Comment by FloresRobles** [comment]
I think that’s the way to go with MagicalRecordLoggingLevelOff as default


  Ing. Javier Ernesto Flores Robles  Montes Blancos 427-1

  Col. Lomas Segunda, C.P. 78210
  San Luis Potosí, SLP

  Telefono 444-210-0918
  Celular 444-848-1114

**Comment by tonyarnold** [comment]
Done. I've made this change (and other changes) in v2.3.0-beta.6. I need to write a few docs, but otherwise it's good to go!

**Comment by FloresRobles** [comment]
:D

**Comment by pronebird** [comment]
Thank you very much for that change!
