### ISSUE TITLE
Swift Project

### ISSUE THREAD

**Issue by Urkman** [magicalpanda/MagicalRecord#993]
Hello,

we are starting a new project and we will use Swift...
So, what Branch should we use for this project?

Thanks,
Urkman

**Comment by tonyarnold** [comment]
`module-support` is the branch you should try to use. I haven't made any time for MagicalRecord lately, but please file issues as you find them on #960 — I'll do my best to fix up anything glaring. Feel free to submit PRs against that branch as well if you find that things aren't working.

**Comment by Urkman** [comment]
Any news on swift compatibility? 
"module-support" is now merged. So are we ready to go with MagicalRecords in a Swift Project?
What are the "best practices" for this?

**Comment by tonyarnold** [comment]
@Urkman there aren't any best practices yet — I haven't even had the chance to really use MR in a Swift project yet. It should work, but let me know what you find — I'm happy to address any glaring issues.
